### DISCUSSION TITLE
Using for non-Docker services?

### DISCUSSION THREAD

**Discussion by alethiophile** [almeidapaulopt/tsdproxy#109] [Q&A]
I have a server with various services, some in Docker, some running on the host directly. I don't particularly want to bother containerizing the host-native services.

Is it possible to set up TSDProxy to proxy to a service running on the host? It looks kind of like you should be able to do this with the proxy list files, but I'm not sure what you would put in the URL.

**Comment by almeidapaulopt** [comment]
yes its possible, see https://almeidapaulopt.github.io/tsdproxy/docs/files/

**Comment by esa1966** [comment]
Hi, I try to find a solution without success.
The link above is broken.
I have a DEBIAN server with TSDProxy and Tailscale
A music server and Home assistant are not dockerized and running on two other linux server and also accessible by DEBIAN server.
Do you think possible to access HA or the music server from a device with client tailscale (tablet).
The goal is to not install Tailscale on each servers (security reason)
Thanks

**Reply by esa1966** [reply]
It's working with v2 and information available here https://almeidapaulopt.github.io/tsdproxy/docs/v2/providers/lists/
Thank a lot
Just a remark : for LYRION (LMS server) it's working without adaptation but for Home assistant  I get bad request 400.
Which mean reject by HA.
It's necessary to add in configuration.yaml for Home Assistant : to trust TSDProxy 

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24 #or the IP where tsdproxy is installed
    - 100.64.0.0/10 #tailscale network (not sure)

```
