### DISCUSSION TITLE
Funnel only

### DISCUSSION THREAD

**Discussion by Tom7320** [almeidapaulopt/tsdproxy#169] [Q&A]
Hi everyone,

probably a stupid question, but I can't figure it out. How can I provide an external website (nginx.funny-name.ts.net) without providing it internally (192.168.10.20:8080) using tailscale funnel? Just remove the `ports` section of the compose.yaml does not work by itself:

```
services:
  web:
    image: nginx
    container_name: nginx-test
    #ports:
    #  - "8080:80"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.funnel: "true"

```

Thx a lot!

Thorsten

**Comment by almeidapaulopt** [comment]
if you have tsdproxy and the container in the same network, it should do

**Comment by Tom7320** [comment]
I tried like so:

```
services:
  web:
    image: nginx
    container_name: nginx-test
    #ports:
    #  - "8080:80"
    networks:
      - tsdproxy_default
    labels:
      tsdproxy.enable: "true"
      tsdproxy.funnel: "true"

networks:
  tsdproxy_default:
    external: true
```

Log:

```
11:45AM INF Container e67f2afa03bada978877de11dab71c34806012e3d5a2e97ec88330b715aeb387 stopped docker=local module=proxymanager
11:45AM INF stopping proxy module=proxymanager name=nginx-test proxyname=nginx-test
11:45AM INF Terminating server module=proxymanager proxyname=nginx-test
11:45AM INF proxy stopped module=proxymanager name=nginx-test proxyname=nginx-test
11:45AM INF Container 2f28f25ecd497ff8071b076c3f4ebe7648ce8be1506dd2ec94b4c6ed81a6c7d2 started docker=local module=proxymanager
11:45AM INF Trying to auto detect target URL container=/nginx-test docker=local module=proxymanager try=0
11:45AM INF Successfully connected using docker network gateway and exposed port address=172.22.0.1 container=/nginx-test docker=local module=proxymanager port=80
11:45AM INF setting up proxy hostname=nginx-test module=proxymanager proxyname=nginx-test
11:45AM INF starting proxy module=proxymanager name=nginx-test proxyname=nginx-test
11:45AM INF tsnet running state path /data/default/nginx-test/tailscaled.state Hostname=nginx-test module=proxymanager tailscale=default
11:45AM INF tsnet starting with hostname "nginx-test", varRoot "/data/default/nginx-test" Hostname=nginx-test module=proxymanager tailscale=default
11:45AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=nginx-test module=proxymanager tailscale=default
11:45AM INF AuthLoop: state is Running; done Hostname=nginx-test module=proxymanager tailscale=default
11:45AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

But still ngnix-test points to a wrong (other) service on the machine.

compose.yaml for tsdproxy:

```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/tsdproxy/data:/data
      - /volume1/docker/tsdproxy/config:/config
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=dash

```
