### DISCUSSION TITLE
Would it work with self-hosted Headscale?

### DISCUSSION THREAD

**Discussion by europacafe** [almeidapaulopt/tsdproxy#2] [General]
Thanks for creating this useful proxy.

I really want to try it. I'm not using Tailscale website for controlling tailscale nodes, instead, I use self-hosted Headscale.

If I'm not wrong, it seems your proxy has nothing to do with Tailscale admin, so it should be working for my setup?

**Comment by almeidapaulopt** [comment]
I've made a commit that should do it, but I don't have time to set a test environment. So in next version please try it.

**Reply by europacafe** [reply]
Thanks a lot.

**Reply by europacafe** [reply]
tailscale client is running native on unraid server (unraid local IP: 192.168.2.93).
headscale as a docker container on my unraid server. It has been working fine with several tailnets.

I have created a docker-compose below and it started running without error.
```
services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    ports:
      - "83:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_CONTROLURL="headscale.mydomain.com"
      - TSDPROXY_AUTHKEY=9482fff2149......25499e6c14e  #generated by command "headscale --user bthoven preauthkeys create"
      - TSDPROXY_HOSTNAME=192.168.2.93 # my unraid server local ip
      - DOCKER_HOST=unix:///var/run/docker.sock
      #- TSDPROXY_AUTHKEYFILE=/run/secrets/authkey # to use docker secrets, Don't use AUTHKEY 
      #- TSDPROXY_DATADIR:/data # defaults to /data
      #- TSDPROXY_LOGLEVEL=info 
      #- TSDPROXY_CONTAINERACCESSLOG=true #enable proxy access log for all active containers
 
      #secrets:
      #- authkey

#secrets:
  #  authkey:
    #file: tsdproxy_authkey.txt

volumes:
  datadir:

```
I also add a label to my working radar container:
```
labels:
  tsdproxy.enable: "true"
```

Below are the log entries after starting tsdproxy container:
```
Initializing server
Version 
Setting up logger
8:18AM INF Log Settings Log level=info
8:18AM INF Starting server Version=
8:18AM INF Setting up proxy for existing containers
8:18AM INF setting up proxy for container containerID=6b3751b9d41bac6836080088a62d30b67b94a7f225a3248ef30850978430f1fc
8:18AM INF Initializing WebServer
8:18AM INF Health check set to ready
8:18AM INF tsnet running state path /data/radarr/tailscaled.state
8:18AM INF tsnet running state path /data/radarr/tailscaled.state
8:18AM INF tsnet running state path /data/radarr/tailscaled.state
8:19AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:19AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:20AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:20AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:21AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
...
```

I can't access "https://radarr.mytailnet.com" from my mobile phone (tailscale is on). It says  
```
Hmmm… can't reach this page
radarr.mytailnet.com’s server IP address could not be found.
```
and no error log from tsdproxy container.

I define "mytailnet.com" as my tailnet main domain with headscale config.

I'm not sure what I did wrong. Need your help....thanks.
