### DISCUSSION TITLE
How to use Portainer with Docker Swarm

### DISCUSSION THREAD

**Discussion by Drallas** [almeidapaulopt/tsdproxy#200] [General]
I'm 'playing' with tsdproxy trying to understand it better; before I'm comfortable to incorporate into my Homelab Prod Environment.

I can run Portainer on a single Node without any issue:

```
  ## tsdproxy
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    ports:
      - "8080:8080"
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
      - ./:/config
    secrets:
      - authkey
    restart: unless-stopped

  ## Portainer  
  portainer:
    image: portainer/portainer-ee:latest
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
      tsdproxy.container_port: "9000"
```

Unfortunately, when I try to modify it for Docker Swarm; Portainer doesn't start any more, even it does create an item in Tailscale:

```
  ## Portainer
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ee:latest
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer"
      tsdproxy.container_port: "9000"
```

What I'm I missing?
