### DISCUSSION TITLE
ERR_SSL_PROTOCOL_ERROR using simple example

### DISCUSSION THREAD

**Discussion by DrConradInTheHouse** [almeidapaulopt/tsdproxy#202] [Q&A]
I followed the guide, "Getting Started", and setup tsdproxy with nginx. Both are  hosted on the same Pi model 3B running raspbian bookworm. Pi ip address is 192.168.0.2. 

**What's working:**

1. Tailscale app on Android, logs in, and I see my machines.
2. On tailscale dashboard, I see the machines.
3. Using a ping app on my mobile, I can ping the tailscale IPV4 addresses for tsdproxy and nginx.
4. When connected to WiFi I can navigate to http:192.168.0.2:80 on my LAN and correctly receive the nginx web server greeting.
5. When I am away from home, fire up the tailscale app, I can use a ping app and ping the tailscale IPV4 addresses successfully. 

**What's not working - help needed please**
When I am away from home, fire up the tailscale app, I open a browser and navigate to the nginx tailscale IPV4 address port 80, so http:100.96.247.36:80 and I get a browser screen showing "The connection for this site is not secure, 100.96.247.36 sent an invalid response" ERR_SSL_PROTOCOL_ERROR.

in the tsdproxy container log, I see the line:
`tsdproxy    | 2025/02/17 12:42:40 http: TLS handshake error from 100.119.135.54:37370: no SNI ServerName`

In summary, I know the servers are running in their docker containers, they are all contactable, and I can get to the nginx welcome screen but only outside the tailscale network when on LAN WiFi. When running tailscale on my Android phone  I am unable to reach the nginx server using its tailscale DNS name or tailscale IPV4 address. **why?**

Obvious some sort of config error but what?

here is my config:

**docker-compose.yaml for tsdproxy**
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
    networks:
      - tailscale

volumes:
  datadir:

networks:
  tailscale:
    name: tailscale
```

**config/tsdproxy.yaml**
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        defaultproxyprovider: default
tailscale:
    providers:
        default:
          authKey: ***
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true

```

**docker-compose.yaml for nginx**
```
version: "3"
services:
  client:
    image: nginx
    container_name: nginx
    ports:
     - 80:80
    networks:
     - tailscale
    labels:
     tsdproxy.enable: "true"
     tsdproxy.name: "nginx" # Optional
     tsdproxy.container_port: 80 # Option

networks:
  tailscale:
    name: tailscale

```
