### DISCUSSION TITLE
Can I Proxy a Container with an IP Different from the Docker Host's IP in the same subnet?

### DISCUSSION THREAD

**Discussion by j4ck3** [almeidapaulopt/tsdproxy#222] [Q&A]
container i want to proxy:
```
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      br0:
        ipv4_address: 192.168.1.53
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
   labels:
      - tsdproxy.enable=true
      - tsdproxy.name=pihole
```

i use the br0 and assign a different ip so i can use defualt ports on my dns resolver (pihole). instead of network_mode: host where these ports is already in use by other processes.

docker inspect br0
```
root@tower:~# docker inspect br0
[
    {
        "Name": "br0",
        "Id": "f8bf7513d275c4287995d9739996282b57bd0a4ab31ac594b0f8f57cc7066a0c",
        "Created": "2025-02-09T13:19:56.086602707-08:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.1.0/24",
                    "Gateway": "192.168.1.1",
                    "AuxiliaryAddresses": {
                        "server": "192.168.1.24"
                    }
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "a5cfa62fb108dff726fbbdc5d232c2f479bc27dd9882f1fd672111e74d54c8a5": {
                "Name": "pihole",
                "EndpointID": "034d182213e06f6048fd13f1a3b9f4925cc51a6d47899e4c0579778c93d43df3",
                "MacAddress": "02:42:c0:a8:01:35",
                "IPv4Address": "192.168.1.53/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "br0"
        },
        "Labels": {}
    }
]
```

what i get in my tsdproxy logs is 
2025/03/16 21:58:14 http: proxy error: dial tcp 192.168.1.53:80: connect: no route to host
9:58PM ERR error host=pihole.tail93a68f.ts.net method=GET module=proxymanager proxyname=pihole status=502 url=/

question is, how to make tsdproxy reach 192.168.1.53?
