### DISCUSSION TITLE
I do not manage to connect to a registered container

### DISCUSSION THREAD

**Discussion by wsw70** [almeidapaulopt/tsdproxy#262] [Q&A]
I would like to seriously get back to tsdproxy after a (semi-failed) first attempt. These are all the steps I did, which ended up with my failure to connect to the container

# Setup

I use a simple nginx installation to do the tests. 
`192.168.10.2` is the docker host
The configuration of tsdproxy is

```
defaultProxyProvider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targetHostname: 192.168.10.2
        defaultProxyProvider: default
lists: {}
tailscale:
    providers:
        default:
            controlUrl: https://controlplane.tailscale.com
            authKey: XXX
            tags: "tag:docker"
    dataDir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyAccessLog: true
```

# Basic nginx container with an exported port

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:80
networks: {}
```

test from the LAN:

```
root@srv ~# curl -o /dev/null -s -w "%{http_code}\n" http://192.168.10.2:8888
200
```

# Addition to tsdproxy

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:80
    labels:
      - tsdproxy.enable=true
networks: {}
```

![image](https://github.com/user-attachments/assets/e6f9f008-bf68-4dba-9dc5-8d9a876461cc)

**A test from tailscale fails:** 

```
> curl -v http://nginx-nginx-1.XXX.ts.net
* Host nginx-nginx-1.XXX.ts.net:80 was resolved.
* IPv6: fd7a:XXX
* IPv4: (none)
*   Trying [fd7a:XXX]:80...
* connect to fd7a:XXX port 80 from :: port 64762 failed: Connection refused
* Failed to connect to nginx-nginx-1.XXX.ts.net port 80 after 7116 ms: Could not connect to server
* closing connection #0
```

The machine from which the `curl` is done is correctly registered with Tailscale

```
> ping srv.XXX.ts.net

Pinging srv.XXX.ts.net [fd7a:1XXX] with 32 bytes of data:
Reply from fd7a:XXX: time=15ms
Reply from fd7a:XXX: time=7ms
```

A ping on the registered address of the container is successful as well.

Adding `tsdproxy.container_port=80` did not help.

The logs on tsdproxy side:

```
tsdproxy-1  | 1:07PM INF Container 0b0e8d44c20d3a22cda010d2cd9f26b286f7bf5e87029ea43021c0e5a37b93ba started docker=local module=proxymanager
tsdproxy-1  | 1:07PM INF setting up proxy hostname=nginx-nginx-1 module=proxymanager proxyname=nginx-nginx-1
tsdproxy-1  | 1:07PM INF starting proxy module=proxymanager proxyname=nginx-nginx-1
tsdproxy-1  | 1:07PM INF tsnet running state path /data/default/nginx-nginx-1/tailscaled.state Hostname=nginx-nginx-1 module=proxymanager tailscale=default
tsdproxy-1  | 1:07PM INF tsnet starting with hostname "nginx-nginx-1", varRoot "/data/default/nginx-nginx-1" Hostname=nginx-nginx-1 module=proxymanager tailscale=default
tsdproxy-1  | 1:07PM INF LocalBackend state is NoState; running StartLoginInteractive... Hostname=nginx-nginx-1 module=proxymanager tailscale=default
tsdproxy-1  | 1:07PM INF AuthLoop: state is Running; done Hostname=nginx-nginx-1 module=proxymanager tailscale=default
```
