### DISCUSSION TITLE
Do I need to map the ports?

### DISCUSSION THREAD

**Discussion by wsw70** [almeidapaulopt/tsdproxy#263] [Q&A]
As I am investigating my problems with TSDproxy , I noticed that the containers that "work" all have their ports mapped.
The ones that do not, do not have the mapping.

Going from 

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:80
    labels:
      - tsdproxy.enable=true
      - tsdproxy.container_port=80
networks: {}
```

to (`ports:` removed)

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:80
    labels:
      - tsdproxy.enable=true
      - tsdproxy.container_port=80
networks: {}
```

breaks the connectivity.

Since TSDproxy is discussion with the containers **at docker level** (and therefore on the docker network) I do not understand why the mapping would be needed.

Note: I tried v1 and v2, with -for v2- `tsdproxy.port: "443/https:80/http"` (I also tried `tsdproxy.port.1: "443/https:80/http"` ( with `.1`))

**Comment by wsw70** [comment]
This is really weird. Here is an example from a container (Gitea) that exposes the service on 3000:

```
  gitea:
    image: gitea/gitea:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.XXX`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - tsdproxy.enable=true
      - tsdproxy.port=443/https:3000/http
    ports:
      - 52001:3000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gitea:/data
```

The above works. If I remove the port binding, it stops to work, **despite 52001 not being referenced in TSDProxy**
