### DISCUSSION TITLE
Porting from v1 to v2 and SSL Warnings

### DISCUSSION THREAD

**Discussion by MrPaulAR** [almeidapaulopt/tsdproxy#264] [Q&A]
I've been running on v1 for some time but wanted to start taking advantage of tags for some ACL rules and I don't think v1 would meet those needs.  And v2 is newer so it's gotta be better even if beta :)

Before getting into the tagging I've noticed that the v2 isn't doing TLS properly.  By that I mean when i visit a container created via v2 I'm getting the TLS warning.  When I was using v1 the only time I saw that was when I was doing a manual device for something outside of docker and fixed it by adding "runWebClient: true" to the `media.yaml` file.

Am I missing something on the v2 that would add this to containers for v2?  Below is my current settings for a sample container.

```
## tsdproxy.yaml

defaultProxyProvider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targetHostname: 192.168.86.25
        tryDockerInternalNetwork: false
lists: {}
tailscale:
    providers:
        default:
            clientId: "..."
            clientSecret: "..."
            controlUrl: https://controlplane.tailscale.com
    dataDir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyAccessLog: true
```

```
## compose.yaml relevant section

  nginx:
    image: nginx
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "nginx"
```

The result of the options above via tailscale to https://nginx.name.ts.net is SSL cert warning.
