### DISCUSSION TITLE
V2.0 Docker Swarm - HTTP 502 Bad Gateway error

### DISCUSSION THREAD

**Discussion by Drallas** [almeidapaulopt/tsdproxy#270] [Q&A]
Going off the [getting-started](https://almeidapaulopt.github.io/tsdproxy/docs/v2/getting-started/) guide, I get TSDProxy Stack running in Docker and active in my Tailnet.
 <br>

<img width="1027" alt="Screenshot 2025-05-07 at 22 34 53" src="https://github.com/user-attachments/assets/43b2c587-0a15-487c-83b9-5b7f934e7bd0" />
 <br> <br>

The Dashboard shows both.
<img width="1470" alt="Screenshot 2025-05-07 at 22 34 15" src="https://github.com/user-attachments/assets/e20bab4f-bfdb-44bd-bf69-e3b67895b43e" />
 <br> 

Unfortunately, when opening the browser, **I'm not getting a certificate**, but a HTTP 502 Bad Gateway error!

<img width="900" alt="Screenshot 2025-05-07 at 22 29 39" src="https://github.com/user-attachments/assets/8699ebeb-10a8-4dff-8004-a257e0870e94" />

<img width="937" alt="Screenshot 2025-05-09 at 22 26 35" src="https://github.com/user-attachments/assets/bbffb0e9-3b14-4a03-bfac-c0b4d5096c07" />

<br>
But via servname:ip the app is accessible.
<img width="900" alt="Screenshot 2025-05-07 at 22 36 38" src="https://github.com/user-attachments/assets/f714d467-d344-4894-bf40-8d35c9e146fc" />

<br>
What I'm a missing?
<br>

**Container log**

```text
8:34PM ERR error client=10.0.0.3:49580 host=dswarm03:8080 method=GET status=404 url=/icons/dist/tsdproxy.svg
8:34PM INF request client=10.0.0.3:49581 host=dswarm03:8080 method=GET status=200 url=/icons/sh/commafeed.svg
8:34PM INF request client=10.0.0.3:49582 host=dswarm03:8080 method=GET status=200 url=/icons/mdi/information-variant.svg
8:34PM INF request client=10.0.0.3:49576 host=dswarm03:8080 method=GET status=200 url=/favicon.ico
8:34PM INF request client=127.0.0.1:58556 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:34PM INF Client disconnected module=dashboard
8:34PM INF request client=10.0.0.3:49579 host=dswarm03:8080 method=GET status=200 url=/stream?datastar=%7B%22theme%22%3Afalse%2C%22search%22%3A%22%22%2C%22user_username%22%3A%22%22%2C%22user_displayName%22%3A%22%22%2C%22user_profilePicUrl%22%3A%22%22%7D
8:35PM INF request client=127.0.0.1:50536 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:35PM ERR error client=10.0.0.4:45972 host=api.ip.pn:443 method=CONNECT status=405 url=//api.ip.pn:443
8:36PM INF request client=127.0.0.1:53190 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:36PM INF New Client connected module=dashboard
8:36PM ERR error client=10.0.0.3:49582 host=dswarm03:8080 method=GET status=404 url=/icons/dist/tsdproxy.svg
8:36PM INF Client disconnected module=dashboard
8:36PM INF request client=10.0.0.3:49576 host=dswarm03:8080 method=GET status=200 url=/stream?datastar=%7B%22theme%22%3Afalse%2C%22search%22%3A%22%22%2C%22user_username%22%3A%22%22%2C%22user_displayName%22%3A%22%22%2C%22user_profilePicUrl%22%3A%22%22%7D
8:37PM INF request client=127.0.0.1:44246 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:38PM INF request client=127.0.0.1:53838 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

```

**docker-stack.yml**

```yml
---
version: "3.8"
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/jfsdocker/docker/volumes/tsdproxy:/data
      - /mnt/jfsdocker/docker/volumes/tsdproxy/v2:/config
    environment:
      - TZ=Europe/Amsterdam
    secrets:
      - source: authkey
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
      placement:
        constraints:
          - node.labels.location == vps
          - node.hostname == dswarm03
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=tsdproxy2"

  commafeed:
    image: athou/commafeed:latest-h2
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: ingress
    volumes:
      - /mnt/jfsdocker/docker/volumes/commafeed:/commafeed/data
    env_file:
      - ../../commafeed/commafeed.env
      - ../../global.env
    security_opt:
      - no-new-privileges:true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
      placement:
        constraints:
          - node.labels.location == vps
          - node.hostname == dswarm03

    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=commafeed2"

secrets:
  authkey:
    external: true

networks:
  default:
    driver: overlay

```

**/config/tsdproxy.yaml**

```yml
defaultProxyProvider: default
docker:
  local: # name of the docker target provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    targetHostname: 172.31.0.1 # hostname or IP of docker server
    defaultProxyProvider: default # name of which proxy provider to use
lists: {}
tailscale:
  providers:
    default: # name of the provider
      authKey: "" # optional, define authkey here
      authKeyFile: "/run/secrets/authkey" # optional, use this to load authkey from file. If this is defined, Authkey is ignored
      controlUrl: https://controlplane.tailscale.com # use this to override the default control URL
  dataDir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access log

```

**Comment by Drallas** [comment]
The same Docker Swarm with TSDProxy V1, with almost the same config as above, works fine! 

<img width="1195" alt="Screenshot 2025-05-07 at 21 40 51" src="https://github.com/user-attachments/assets/00b4d8aa-0151-4710-beb2-50451e38c64d" />

<img width="965" alt="Screenshot 2025-05-07 at 21 42 30" src="https://github.com/user-attachments/assets/57e30baa-5ab4-40f8-9c51-ca45e9c74ce8" />


```yml
---
version: "3.8"
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/jfsdocker/docker/volumes/tsdproxy:/data
      - /mnt/jfsdocker/docker/volumes/tsdproxy/v1:/config
    environment:
      - TZ=Europe/Amsterdam
    secrets:
      - source: authkey
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M
      placement:
        constraints:
          - node.labels.location == vps
          - node.hostname == dswarm04
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=tsdproxy1"

  commafeed:
    image: athou/commafeed:latest-h2
    ports:
      - target: 8082
        published: 8082
        protocol: tcp
        mode: ingress
    volumes:
      - /mnt/jfsdocker/docker/volumes/commafeed:/commafeed/data
    env_file:
      - ../../commafeed/commafeed.env
      - ../../global.env
    security_opt:
      - no-new-privileges:true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.25"
          memory: 128M
      placement:
        constraints:
          - node.labels.location == vps
          - node.hostname == dswarm04
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=**commafeed1**"

secrets:
  authkey:
    external: true

networks:
  default:
    driver: overlay
```

```yml
defaultProxyProvider: default
docker:
  local: # name of the docker target provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    targetHostname: 172.31.0.1 # hostname or IP of docker server
    defaultProxyProvider: default # name of which proxy provider to use
files: {}
tailscale:
  providers:
    default: # name of the provider
      authKey: "" # optional, define authkey here
      authKeyFile: "/run/secrets/authkey" # optional, use this to load authkey from file. If this is defined, Authkey is ignored
      controlUrl: https://controlplane.tailscale.com # use this to override the default control URL
  dataDir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access log
```
