### DISCUSSION TITLE
Multiple tsdproxy v2 instances interfering with each other

### DISCUSSION THREAD

**Discussion by CatLover01** [almeidapaulopt/tsdproxy#287] [Q&A]
## Environment
- tsdproxy version: v2
- Docker/Docker Compose for deployment

## Issue Description
I'm experiencing an unusual interaction between two separate tsdproxy v2 instances. When starting one instance, it inexplicably triggers or duplicates the other instance.

Specifically, I have two separate tsdproxy configurations:
1. A "shared" provider configuration
2. A "private" provider configuration

Each has its own directory and configuration file, but when I start the "shared" instance with `docker compose up`, it somehow also creates a duplicate of my "private" instance.

## What I'm observing
- The container for my "shared" instance never appears in `https://login.tailscale.com/admin/machines`
- Instead, I see a duplicate of my "private" instance appearing with "service-1" and a "-1" suffix
- This suggests the "shared" instance is somehow triggering or copying the "private" instance

## Configuration
Here's my configuration for the "shared" proxy:

```yaml
defaultProxyProvider: shared
docker:
  shared_docker: 
    host: unix:///var/run/docker.sock
    targetHostname: host.docker.internal 
    defaultProxyProvider: shared
lists: {}
tailscale:
  providers:
    shared:
      clientId: "id..."
      clientSecret: "authkey..."
  dataDir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info
  json: false
proxyAccessLog: true
```

My "private" configuration is identical, except it uses "private" instead of "shared" in the provider settings.

## Questions
1. Why would starting one tsdproxy instance trigger or duplicate another separate instance?
2. Is there something in my configuration that could be causing this cross-instance interference?
3. How can I properly isolate multiple tsdproxy v2 instances running on the same host?

Any insights would be greatly appreciated!

---

More information about the labels used can be found [here](https://www.reddit.com/r/Tailscale/comments/1l0y0qm/help_using_tsproxy_with_plane_app_adding_tsproxy/)
