### DISCUSSION TITLE
Help :: Basic example does not work for me

### DISCUSSION THREAD

**Discussion by optimistic5** [almeidapaulopt/tsdproxy#297] [Q&A]
Here is my `tsdproxy.yaml` config
```
defaultProxyProvider: default
docker:
  local: # name of the docker target provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    defaultProxyProvider: default # name of which proxy provider to use
tailscale:
  providers:
    default: # name of the provider
      authKey: "tskey-auth-my-key-here" # define authkey here
```
Here is `compose.yml`
```
services:

  tsdproxy:
    image: almeidapaulopt/tsdproxy@sha256:88cc82593f31acc50e998e01839532958326b91344aefc1437f7f55a54ccd515
    volumes:
      - ./tsdproxy.yaml:/config/tsdproxy.yaml
      - tsdproxydata:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  nginx-test:
    image: nginx:latest
    ports:
      - 81:80
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "test"

volumes:
  tsdproxydata:
 ```
1. **Issue that it does not work. What I do wrong?**
I do 
```
curl https://test.foo-bar.ts.net
```
Here the log
```
tsdproxy-1    | Initializing server
tsdproxy-1    | Version 2.0.0-dev
tsdproxy-1    | loading configuration from: /config/tsdproxy.yaml
tsdproxy-1    | Validating configuration...
tsdproxy-1    | Setting up logger
tsdproxy-1    | 7:45AM INF Log Settings Log level=info
tsdproxy-1    | 7:45AM INF Starting server Version=2.0.0-dev
tsdproxy-1    | 7:45AM INF Setting up proxy proxies
tsdproxy-1    | 7:45AM INF Initializing WebServer
tsdproxy-1    | 7:45AM INF Health check set to ready
tsdproxy-1    | 7:45AM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
tsdproxy-1    | 7:45AM INF Container 9d66625216911d5bab604039eb9fcc054396a189b8f3d6c62c0172e6bba12c9c started docker=local module=proxymanager
tsdproxy-1    | 7:45AM INF setting up proxy hostname=test module=proxymanager proxyname=test
tsdproxy-1    | 7:45AM INF starting proxy module=proxymanager proxyname=test
tsdproxy-1    | 7:45AM INF tsnet running state path /data/default/test/tailscaled.state Hostname=test module=proxymanager tailscale=default
tsdproxy-1    | 7:45AM INF tsnet starting with hostname "test", varRoot "/data/default/test" Hostname=test module=proxymanager tailscale=default
tsdproxy-1    | 7:45AM INF Authkey is set; but state is NoState. Ignoring authkey. Re-run with TSNET_FORCE_LOGIN=1 to force use of authkey. Hostname=test module=proxymanager tailscale=default
tsdproxy-1    | 7:45AM INF AuthLoop: state is Running; done Hostname=test module=proxymanager tailscale=default
tsdproxy-1    | 7:46AM INF request client=127.0.0.1:33676 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
tsdproxy-1    | 7:47AM INF request client=127.0.0.1:37932 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
tsdproxy-1    | 2025/06/17 07:48:12 http: proxy error: dial tcp 172.31.0.1:81: connect: connection timed out
tsdproxy-1    | 7:48AM ERR error client=100.79.123.99:46366 host=test.foo-bar.ts.net method=GET module=proxymanager port=443/https:80/http proxyname=test status=502 url=/
```
(I changed my tailnet name to `foo-bar` here)

2. Another Question.
**How to make it work without exposing ports?**
It make no sense to do in my VPS, because this port is exposing to all internet. (I do not want to play with firewalls for docker).
Here the log if my `nginx-test` with no `ports` section.
Tailscale service does not even creates in this case.

```
tsdproxy-1    | Initializing server
tsdproxy-1    | Version 2.0.0-dev
tsdproxy-1    | loading configuration from: /config/tsdproxy.yaml
tsdproxy-1    | Validating configuration...
tsdproxy-1    | Setting up logger
tsdproxy-1    | 7:44AM INF Log Settings Log level=info
tsdproxy-1    | 7:44AM INF Starting server Version=2.0.0-dev
tsdproxy-1    | 7:44AM INF Setting up proxy proxies
tsdproxy-1    | 7:44AM INF Initializing WebServer
tsdproxy-1    | 7:44AM INF Health check set to ready
tsdproxy-1    | 7:44AM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
tsdproxy-1    | 7:44AM INF Container 5fbab504cfabf442b62d3331d1cab2d684659f74f6b35d80e58ad2526ea87f23 started docker=local module=proxymanager
tsdproxy-1    | 7:44AM INF setting up proxy hostname=test module=proxymanager proxyname=test
tsdproxy-1    | 7:44AM INF starting proxy module=proxymanager proxyname=test
tsdproxy-1    | 7:44AM WRN No ports configured module=proxymanager proxyname=test
```
