### DISCUSSION TITLE
TSDProxy cannot talk to internal services

### DISCUSSION THREAD

**Discussion by joelschou** [almeidapaulopt/tsdproxy#47] [Q&A]
• Mac mini M2
• MacOS 15.1.1 (latest)
• Podman 5.3.0 (latest)

It took some finagling, but I finally got TSDProxy running with this compose setup:

```yaml
services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:latest
    privileged: true
    labels:
      - tsdproxy.container_port=8080
      - tsdproxy.enable=true
      - tsdproxy.name=tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
    restart: unless-stopped
    environment:
      # Get AuthKey from your Tailscale account
      - TSDPROXY_AUTHKEY=tskey-auth-<KEY>
      # Address of docker server (access to example.com ports)
      - TSDPROXY_HOSTNAME=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      # https://github.com/almeidapaulopt/tsdproxy/issues/33
      - STATE_DIRECTORY=/data
volumes:
  datadir:
```

I have a few Node apps running on ports in the 3000s. I also have the `sample-nginx` container running from the quick start docs.

I can see `tsdproxy`, `tsdproxy-tailscale-docker-proxy-1`, `nodeapp`, and `sample-nginx` in my list of Tailscale machines. 

I can also see the services running when I visit the TSDProxy dashboard: 

```html
<!-- https://tsdproxy.<silly-name>.ts.net -->

https://nodeapp https://sample-nginx https://tsdproxy
```

However, any time I try to visit one of these services, it fails and I get a connection error in my logs.

```log
tailscale-docker-proxy-1  | 2024/11/19 20:35:36 http: proxy error: dial tcp [::1]:3001: connect: connection refused
tailscale-docker-proxy-1  | 8:35PM ERR error host=nodeapp.<silly-name>.ts.net method=GET status=502 url=/

tailscale-docker-proxy-1  | 2024/11/19 20:37:51 http: proxy error: dial tcp xx.xx.x.x:8181: connect: connection refused
tailscale-docker-proxy-1  | 8:37PM ERR error host=sample-nginx.<silly-name>.ts.net method=GET status=502 url=/
```

I've tried to define networks (https://github.com/almeidapaulopt/tsdproxy/discussions/43) but that doesn't do the trick either (the node app has a network configured). Any suggestions?
