### DISCUSSION TITLE
Second docker service

### DISCUSSION THREAD

**Discussion by bozzio83** [almeidapaulopt/tsdproxy#86] [Q&A]
I'm just trying to figure out which IP to put in the tsdproxy.yaml of my second docker server.  It is already on my tailnet and I've tried that IP but am really struggling with getting it connected.  I'm sure its something simple but I cannot figure it out. 
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
        defaultproxyprovider: default
    local2:
        host: tcp://192.168.1.139
files: {}
tailscale:
    providers:
        default:
            authkey: tskey-auth-**************************************
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```
