### ISSUE TITLE
status=502 when accessing applications 

### ISSUE THREAD

**Issue by svenvg93** [almeidapaulopt/tsdproxy#105]
First of all thanks for creating this amazing application! Im loving it! 

Unfortunately I'm running into a weird problem. After using it for weeks with just one application to test, I wanted to added more applications to it. I added the needed labels and set the same docker network in the compose files and re-deployed them. 

They all show up in the Tailscale Admin panel, but I can't load the WebGui's of these applications, not even the one that was working before. 

Below are the logs;

```
 module=proxymanager tailscale=default
2024/12/18 17:26:55 http: proxy error: dial tcp 172.31.0.1:80: connect: no route to host
5:26PM ERR error host=speedtest-tracker.tailxxxxx.ts.net method=GET module=proxymanager proxyname=speedtest-tracker status=502 url=/
5:27PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
5:27PM TRC wg: [v2] [2WrW8] - Sending keepalive packet module=proxymanager tailscale=default
5:27PM TRC wgengine: idle peer [2WrW8] now active, reconfiguring WireGuard module=proxymanager tailscale=default
5:27PM TRC wgengine: Reconfig: configuring userspace WireGuard config (with 1/7 peers) module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - UAPI: Created module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - UAPI: Updating endpoint module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - UAPI: Removing all allowedips module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - Starting module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - Received handshake initiation module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - Sending handshake response module=proxymanager tailscale=default
5:27PM TRC [v1] magicsock: derp route for [2WrW8] set to derp-14 (shared home) module=proxymanager tailscale=default
5:27PM TRC [v1] Accept: TCP{100.91.241.99:50393 > 100.80.20.240:80} 64 tcp ok
 module=proxymanager tailscale=default
5:27PM TRC netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=false portmap= v4a=92.254.xxx.xxx:57563 derp=14 derpdist=4v4:16ms,8v4:17ms,14v4:10ms module=proxymanager tailscale=default
2024/12/18 17:27:10 http: proxy error: dial tcp 172.31.0.1:80: connect: no route to host
5:27PM ERR error host=beszel.tailxxxxx.ts.net method=GET module=proxymanager proxyname=beszel status=502 url=/
5:27PM TRC netcheck: [v1] report: udp=true v6=false v6os=true mapvarydest=false portmap= v4a=92.254.xxx.xxxx:46624 derp=14 derpdist=4v4:15ms,8v4:16ms,14v4:10ms module=proxymanager tailscale=default
5:27PM TRC wg: [v2] [2WrW8] - Sending keepalive packet module=proxymanager tailscale=default
6:02PM TRC control: lite map update error after 2m0.001s: Post "https://controlplane.tailscale.com/machine/map": context canceled module=proxymanager tailscale=default
```

tsdproxy.yaml:

```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        defaultproxyprovider: default
files: {}
tailscale:
    providers:
        default:
            authkey: ""
            authkeyfile: "/config/authkey"
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: trace
    json: false
proxyaccesslog: true

```

Tailscale itself seem to be working fine, I can reach all my machine
