### ISSUE TITLE
Accessing Docker containers is not working

### ISSUE THREAD

**Issue by Vexz00** [almeidapaulopt/tsdproxy#106]
Host: Synology DS1019+

Compose script used for TSDProxy in Portainer:
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: TSDProxy
    network_mode: host
    environment:
      - TSDPROXY_AUTHKEY=<My auth key>
      - TSDPROXY_HOSTNAME=<Tailnet IP of my NAS>
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/TSDProxy/data:/data
      - /volume1/docker/TSDProxy:/config
    restart: always
```

Labels used in compose scripts when deploying a container:
```
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "speaking-name"
      tsdproxy.ephemeral: "true"
```

In the machines overview in Tailscale I can see the container has been added and is connected. I can't access it with the FQDN though. What I immediately notice, however, is that in the version column it says `1.78.1-ERR-BuildInfo`.

Am I just doing something wrong or is this a bug?
