### ISSUE TITLE
Stacks with multiple services are not accessible

### ISSUE THREAD

**Issue by Vexz00** [almeidapaulopt/tsdproxy#107]
Some of my docker containers are accessible thanks to TSDProxy, but they are all stacks with a single service. None of my stacks (just two at the moment) with multiple services are accessible.

Here's my compose script for Paperless-ngx:
```
services:
  broker:
    image: redis
    container_name: Paperless-ngx-Redis
    restart: always
    volumes:
      - /volume1/docker/Paperless-ngx/redis:/data

  db:
    image: postgres:16
    container_name: Paperless-ngx-DB
    restart: always
    volumes:
      - /volume1/docker/Paperless-ngx/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: <censored user>
      POSTGRES_PASSWORD: <censored password>

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: Paperless-ngx
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8777:8000
    volumes:
      - /volume1/docker/Paperless-ngx/data:/usr/src/paperless/data
      - /volume1/Privates/Paperless-ngx Medien/media:/usr/src/paperless/media
      - /volume1/docker/Paperless-ngx/export:/usr/src/paperless/export
      - /volume1/Privates/Paperless-ngx Medien/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1043
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_FILENAME_FORMAT: '{created_year}/{created_month_name}/{correspondent}/{title}'
      PAPERLESS_ADMIN_USER: <censored user>
      PAPERLESS_ADMIN_PASSWORD: <censored password>
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "paperless-ngx"
      tsdproxy.ephemeral: "true"
```
The container is accessible from my LAN just fine. When I try to access it with MagicDNS in my browser, I just get a simple "Not found" text and nothing else.

Here's the compose script of the other stack, Jitsi Meet:
```
services:
# Frontend
  jitsi-web:
    image: jitsi/web:stable-8960-1
    container_name: Jitsi-Web
    ports:
      - 8084:80
      - 4484:443
    volumes:
      - /volume1/docker/Jitsi/web/config:/config:rw
      - /volume1/docker/Jitsi/web/letsencrypt:/etc/letsencrypt:rw
      - /volume1/docker/Jitsi/web/var:/var:rw
      - /volume1/docker/Jitsi/transcripts://usr/share/jitsi-meet/transcripts:rw
    environment: 
      - TZ=Europe/Berlin
      - JICOFO_AUTH_USER=<censored user>
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "jitsi"
      tsdproxy.ephemeral: "true"
      tsdproxy.funnel: "true"
    restart: on-failure:5

# XMPP server
  jitsi-prosody:
    image: jitsi/prosody:stable-8960-1
    container_name: xmpp.meet.jitsi
    ports:
      - 5222:5222
      - 5280:5280
      - 5347:5347
    volumes:
      - /volume1/docker/Jitsi/prosody/config:/config:rw
      - /volume1/docker/Jitsi/prosody/prosody-plugins-custom:/prosody-plugins-custom:rw
    environment: 
      - TZ=Europe/Berlin
      - JICOFO_AUTH_USER=<censored user>
      - JICOFO_AUTH_PASSWORD=<censored password>
      - JVB_AUTH_USER=<censored user>
      - JVB_AUTH_PASSWORD=<censored password>
    restart: on-failure:5

# Focus component
  jitsi-jicofo:
    image: jitsi/jicofo:stable-8960-1
    container_name: Jitsi-Conference-Focus
    volumes:
      - /volume1/docker/Jitsi/jicofo:/config:rw
    depends_on:
      - jitsi-prosody
    environment: 
      - TZ=Europe/Berlin
      - JICOFO_AUTH_USER=<censored user>
      - JICOFO_AUTH_PASSWORD=<censored password>
    restart: on-failure:5

# Video bridge
  jitsi-jvb:
    image: jitsi/jvb:stable-8960-1
    container_name: Jitsi-Video-Bridge
    ports:
      - 8085/udp
      - 8085:8085
    volumes:
      - /volume1/docker/Jitsi/jvb:/config:rw
    depends_on:
      - jitsi-prosody
    environment: 
      - TZ=Europe/Berlin
      - JVB_AUTH_USER=<censored user>
      - JVB_AUTH_PASSWORD=<censored password>
      - DOCKER_HOST_ADDRESS=10.0.0.2
    restart: on-failure:5

# Etherpad: real-time collaborative document editing
  jitsi-etherpad:
    image: jitsi/etherpad:latest
    container_name: Jitsi-Etherpad
    restart: on-failure:5
```
In this case I get a `400 Bad Request: The plain HTTP request was sent to HTTPS port`. I tried adding `tsdproxy.container_port: 443` in the labels, but I get the same error.

**Comment by Vexz00** [comment]
Okay, update time.

With some tweaks I finally made Paperless-ngx work now. That problem is solved.

With Jitsi, it works now too, but I had to disable websocket connections or else I'd immediately disconnect when I try to join a meeting. So I guess websockets in TsDProxy are not yet a thing. Will that be added in the future?

**Comment by ericxob77** [comment]
I am also getting `400 Bad Request: The plain HTTP request was sent to HTTPS port` for one of my containers.  Did upi find a  specific workaround for this?

**Comment by ericxob77** [comment]
Hmm.  That makes no difference for me.  Thanks.

**Comment by almeidapaulopt** [comment]
try https://almeidapaulopt.github.io/tsdproxy/docs/docker/#tsdproxytlsvalidate . I've only noticed now that your using port 443 on target

**Comment by almeidapaulopt** [comment]
Do you have any update? can I close?

**Comment by ericxob77** [comment]
Thanks for checking in with me.

Since I actually have no idea what is causing my problems, you might as
well close this particular issue.

Thanks,

eo

**Comment by mbadros** [comment]
@ericxob77 Would you mind sharing the final compose file that allowed you to get paperless-ngx working with tsdproxy?
Thanks!

**Comment by Vexz00** [comment]
@mbadros 
Sorry I don't have it anymore. I use my NAS as exit node, which is why I can access Paperless-ngx without the need to have it connected to the Tailnet.
What I did back then is checking the container's logs and then do some research about the errors. That helped me to fix the problem. It was like two or three additional environment variables, which did the trick. I can't recall the variables though. Hope that helps you in the right direction to solve the problem.

**Comment by rmonk** [comment]
I had the same issue, it was autodetect.  Relevant working configuration in paperless compose file:
```
labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "paperless"
      tsdproxy.port: 8000
      tsdproxy.autodetect: "false"

```

I thought it was the PAPERLESS_URL or setting the X_FORWARD variables for paperless, but when I removed those it still worked just fine.

So far autodetect has done nothing but cause issues for me, I have to turn it off every time or else I get random errors like this.
