### ISSUE TITLE
Proxy list TLS handshake error cant access the service outside

### ISSUE THREAD

**Issue by runerally** [almeidapaulopt/tsdproxy#110]
Hi. Im trying to setup a service on a different host using proxy list but it throws this message and I can access my service.

Message:
```
http: TLS handshake error from xxx.xxx.xxx.xxx:56889: 500 Internal Server Error: SetDNS "_acme-challenge.service.funny.ts.net" => "random_string": set-dns response: 500 Internal Server Error, context canceled
REQ-string
```

Docker compose:
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
networks: {}
volumes:
  datadir: null
```

config.yaml:
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: xxx.xxx.xxx.xxx
        defaultproxyprovider: default
file: {}
tailscale:
    providers:
        default:
            authkey: tskey-
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: debug
    json: false
proxyaccesslog: true
Files:
  media:
    Filename: /config/media.yaml
    DefaultProxyProvider: default
    DefaultProxyAccessLog: true
```

media.yaml:
```
service:
  url: http://xxx.xxx.xxx.xxx:8999
```

It seems to pickup the right port and the service appears on my tailnet.

Thanks i advance.
