### ISSUE TITLE
Funnels no longer working with version 1.2.0

### ISSUE THREAD

**Issue by Vexz00** [almeidapaulopt/tsdproxy#114]
The [Funnel functionality](https://tailscale.com/kb/1223/funnel) no longer works with TsDProxy version 1.2.0.
Restarting and redeploying TsDProxy in Docker and the container I want to funnel didn't help. Going back to version 1.1.2 fixed the problem, so it must be the changes that came with version 1.2.0.

This is the compose script for the container I want to funnel:
```
services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: Bitwarden
    network_mode: "bridge"
    environment:
      - TZ=Europe/Berlin
      - ADMIN_TOKEN=<censored token>
    volumes:
      - /volume1/docker/Bitwarden:/data
    ports:
      - 3012:3012
      - 5151:80
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "bitwarden"
      tsdproxy.ephemeral: "true"
      tsdproxy.funnel: "true"
    restart: always
```

And here's my TsDProxy compose script:
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1.1.2
    container_name: TsDProxy
    network_mode: host
    environment:
      - TSDPROXY_AUTHKEY=<censored authkey>
      - TSDPROXY_HOSTNAME=100.125.102.121
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/TsDProxy/data:/data
      - /volume1/docker/TsDProxy:/config
    restart: always
```

This is the tsdproxy.yaml file as requested:
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 100.125.102.121
        defaultproxyprovider: default
files: {}
tailscale:
    providers:
        default:
            authkey: <censored authkey>
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```

TsDProxy logs **version 1.2.0**:
```
Initializing server
Version 1.2.0
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
3:11PM INF Log Settings Log level=info
3:11PM INF Starting server Version=1.2.0
3:11PM INF Setting up proxy proxies
3:11PM INF Initializing WebServer
3:11PM INF Health check set to ready
3:11PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
3:11PM ERR No Target Providers found module=proxymanager
3:11PM INF Trying to auto detect target URL container=/Bitwarden docker=local module=proxymanager try=0
3:11PM INF Successfully connected using internal ip and internal port address=172.17.0.4 container=/Bitwarden docker=local module=proxymanager port=80
3:11PM INF setting up proxy hostname=bitwarden module=proxymanager
3:11PM INF starting proxy module=proxymanager name=bitwarden proxyname=bitwarden
3:11PM INF tsnet running state path /data/default/bitwarden/tailscaled.state module=proxymanager tailscale=default
3:11PM INF tsnet starting with hostname "bitwarden", varRoot "/data/default/bitwarden" module=proxymanager tailscale=default
3:11PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
3:11PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
3:12PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

Maybe irrelevant, but perhaps it helps to see the difference between the logs for **version 1.1.2**:
```
Initializing server
Version 
3:15PM INF Log Settings Log level=info
3:15PM INF Starting server Version=
3:15PM INF Setting up proxy proxies
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
3:15PM INF Initializing WebServer
3:15PM INF Health check set to ready
3:15PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
3:15PM ERR No Target Providers found module=proxymanager
3:15PM INF Trying to auto detect target URL container=/Bitwarden docker=local module=proxymanager try=0
3:15PM INF Successfully connected using internal ip and internal port address=172.17.0.4 container=/Bitwarden docker=local module=proxymanager port=80
3:15PM INF setting up proxy hostname=bitwarden module=proxymanager
3:15PM INF starting proxy module=proxymanager name=bitwarden proxyname=bitwarden
3:15PM INF tsnet running state path /data/default/bitwarden/tailscaled.state module=proxymanager tailscale=default
3:15PM INF tsnet starting with hostname "bitwarden", varRoot "/data/default/bitwarden" module=proxymanager tailscale=default
3:15PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
3:15PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
3:15PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
3:16PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
3:16PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
3:17PM INF request host=bitwarden.<censored>.ts.net method=GET module=proxymanager proxyname=bitwarden status=200 url=/
3:17PM INF request host=bitwarden.<censored>.ts.net method=GET module=proxymanager proxyname=bitwarden status=200 url=/api/organizations/undefined/policies/token?token=undefined&email=undefined&organizationUserId=undefined
3:17PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```
