### ISSUE TITLE
unable to validate API key

### ISSUE THREAD

**Issue by dcgsteve** [almeidapaulopt/tsdproxy#124]
Simple example fails to use AUTH key?

Docker:
almeidapaulopt/tsdproxy:latest  (ce47c341e816)

compose.yaml:
```
services:

  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    restart: unless-stopped

  nginx1:
    image: nginx
    ports:
      - 8111:80
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=nginx1"
```

created config directory under current directory and added `tsdproxy.yaml` file (as it's not automatically created)
(NB. Key below is now revoked so leaving in to make sure formatting etc. is ok)

```
defaultProxyProvider: default
docker:
  local: # name of the docker provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    #targetHostname: 192.168.212.163 # hostname or IP of docker server
    defaultProxyProvider: default # name of which proxy provider to use
file: {}
tailscale:
  providers:
    default: # name of the provider
      authKey: tskey-auth-kDeAxiFmRz11CNTRL-p5WfkNwm7u57aWrxXZAuu5fPb4W8RRY2
      authKeyFile: "" # use this to load authkey from file. If this is defined, Authkey is ignored
      controlUrl: https://controlplane.tailscale.com # use this to override the default control URL
  dataDir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access l
```

No errors when starting up proxy and when I start up nginx I get the following:

```
tsdproxy-1  | Initializing server
tsdproxy-1  | Version 1.2.1
tsdproxy-1  | loading configuration from: /config/tsdproxy.yaml
tsdproxy-1  | Validating configuration...
tsdproxy-1  | Setting up logger
tsdproxy-1  | 2:23PM INF Log Settings Log level=info
tsdproxy-1  | 2:23PM INF Starting server Version=1.2.1
tsdproxy-1  | 2:23PM INF Setting up proxy proxies
tsdproxy-1  | 2:23PM INF Initializing WebServer
tsdproxy-1  | 2:23PM INF Health check set to ready
tsdproxy-1  | 2:23PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
nginx1-1    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx1-1    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx1-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
tsdproxy-1  | 2:23PM INF Container 6273d145b5211b5883ac6a62577e4022db3fa42747bc02e0fef7b7d95340cb56 started docker=local module=proxymanager
nginx1-1    | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
nginx1-1    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx1-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
tsdproxy-1  | 2:23PM INF Trying to auto detect target URL container=/tsdproxy-nginx1-1 docker=local module=proxymanager try=0
tsdproxy-1  | 2:23PM INF Successfully connected using docker network gateway and exposed port address=172.20.0.1 container=/tsdproxy-nginx1-1 docker=local module=proxymanager port=8111
tsdproxy-1  | 2:23PM INF setting up proxy hostname=nginx1 module=proxymanager
tsdproxy-1  | 2:23PM INF starting proxy module=proxymanager name=nginx1 proxyname=nginx1
nginx1-1    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx1-1    | /docker-entrypoint.sh: Configuration complete; ready for start up
tsdproxy-1  | 2:23PM INF tsnet running state path /data/default/nginx1/tailscaled.state module=proxymanager tailscale=default
tsdproxy-1  | 2:23PM INF tsnet starting with hostname "nginx1", varRoot "/data/default/nginx1" module=proxymanager tailscale=default
nginx1-1    | 2024/12/26 14:23:32 [notice] 1#1: using the "epoll" event method
```

However, after a pause I then get this and the proxy for nginx is stopped:

```
tsdproxy-1  | 2:24PM ERR Error Listening on TLS error="tsnet.Up: backend: invalid key: unable to validate API key" module=proxymanager proxyname=nginx1
tsdproxy-1  | 2:24PM INF stopping proxy module=proxymanager name=nginx1 proxyname=nginx1
tsdproxy-1  | 2:24PM INF proxy stopped module=proxymanager name=nginx1 proxyname=nginx1
```

I've also tried running nginx container outside of compose. I've also temporarily removed the config file completely and confirmed that the proxy server does then bring up an error (so I'm guessing I have the right location and file name)

Can anyone point me in the right direction for a solution please?

Note: I've rec-created AUTHKEY a couple of times to make sure, plus used an API key instead in case I misunderstood (pretty sure it's AUTHKEY though). Tried ephemeral key plus keys with and without TAG
