### ISSUE TITLE
Does not proxy more than one port

### ISSUE THREAD

**Issue by avidrissman** [almeidapaulopt/tsdproxy#126]
**Describe the bug**
I use Fasten Health, and it exposes two ports: 8080 and 5001. Apparently the frontend relies on both, so when I say

```
        ports:
            - 8080
            - 5001
        labels:
            tsdproxy.enable: "true"
            tsdproxy.name: "fastenhealth"
            tsdproxy.container_port: 8080
```

When I go to the main page, it errors out that port 5001 is not available.

**Expected behavior**
tsdproxy should proxy all ports, not just the main one. 

**Send config**
```
defaultproxyprovider: default
docker:
  local: # name of the docker provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    targethostname: 192.168.1.10 # hostname or IP of docker server
    defaultproxyprovider: default # name of which proxy provider to use
tailscale:
  providers:
    default: # name of the provider
      authkey: nope # define authkey here
      authkeyfile: "" # use this to load authkey from file. If this is defined, Authkey is ignored
      controlurl: https://controlplane.tailscale.com # use this to override the default control URL
  datadir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyaccesslog: true # set to true to enable container access log
```

**Logs**
Weirdly, the attempt to hit port 5001 didn’t show in the logs
