### ISSUE TITLE
Getting Started page has invalid `tsdproxy.yaml`

### ISSUE THREAD

**Issue by avidrissman** [almeidapaulopt/tsdproxy#127]
**Describe the bug**
On https://almeidapaulopt.github.io/tsdproxy/docs/getting-started/ , there is a sample yaml file listed under the “Configure TSDProxy” section, and it has a “file” key:

```
...
  local: # name of the docker provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    targetHostname: 172.31.0.1 # hostname or IP of docker server
    defaultProxyProvider: default # name of which proxy provider to use
file: {}
tailscale:
  providers:
    default: # name of the provider
      authKey: your-authkey # define authkey here
...
```
There is a new version of TSDProxy (1.3.0) and it does not like this key.

Expected:
The sample files in the documentation should work on the most recent version of TSDProxy.

Actual:
When you run TSDProxy 1.3 with that sample config file it errors out:

```
Initializing server
Version 1.3.0
loading configuration from: /config/tsdproxy.yaml
error: yaml: unmarshal errors:
  line 7: field file not found in type config.config
```

Removing the “file” key allows TSDProxy to start.
