### ISSUE TITLE
Unable to connect to containers through Tailscale network despite successful registration

### ISSUE THREAD

**Issue by raev33** [almeidapaulopt/tsdproxy#132]
I'm having issues connecting to my containers through the Tailscale network. I've followed the documentation but cannot identify where the problem lies.

Current Setup:

Attempted to connect via Android phone and laptop, both unsuccessful

- Trying to access Jellyfin and Home Assistant containers (both working fine on local network)
- Enabled HTTPS in Tailscale settings as required for TSDProxy(?)
- Both containers use "network_mode: host"
- Added labels to containers:

```
labels:
    tsdproxy.enable: "true"
    tsdproxy.container_port: 8080
```

Docker Compose configuration:

```
services:
  tsdproxy:
    container_name: tsdproxy
    image: almeidapaulopt/tsdproxy:latest
    environment:
      - "TZ=Europe/Copenhagen"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - "path/to/my/config:/config"
    restart: unless-stopped

volumes:
  datadir:
```

TSDProxy configuration (tsdproxy.yaml):

```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
        defaultproxyprovider: default
files: {}
tailscale:
    providers:
        default:
            authkey: my-key
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```

Expected Behavior:

- When connected to the Tailscale network from an external device, I should be able to access Jellyfin at 100.110.35.84:8096 (Tailscale-assigned IP)

Actual Behavior:

- Containers are registered as machines in Tailscale
- Cannot connect to containers using Tailscale-assigned IPs
- As per https://github.com/almeidapaulopt/tsdproxy/issues/66, I've enabled "remote connections" and set filtermode to "blacklist", but still no success

TSDProxy logs (with only Jellyfin container running for simplicity):

```
Initializing server
Version 1.3.1
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
9:12AM INF Log Settings Log level=info
9:12AM INF Starting server Version=1.3.1
9:12AM INF Setting up proxy proxies
9:12AM INF Initializing WebServer
9:12AM INF Health check set to ready
9:12AM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
9:12AM INF Container 7ec6a17e8b3e664f4c83186d9460778f85963ceb9ca2bf3cbaaa7f391d2ee6ed started docker=local module=proxymanager
9:12AM INF Trying to auto detect target URL container=/jellyfin docker=local module=proxymanager try=0
9:12AM INF Successfully connected using defaultBridgeAddress and internal port address=172.17.0.1 container=/jellyfin docker=local module=proxymanager port=8096
9:12AM INF setting up proxy hostname=jellyfin module=proxymanager
9:12AM INF starting proxy module=proxymanager name=jellyfin proxyname=jellyfin
9:12AM INF tsnet running state path /data/default/jellyfin/tailscaled.state module=proxymanager tailscale=default
9:12AM INF tsnet starting with hostname "jellyfin", varRoot "/data/default/jellyfin" module=proxymanager tailscale=default
9:12AM INF Authkey is set; but state is NoState. Ignoring authkey. Re-run with TSNET_FORCE_LOGIN=1 to force use of authkey. module=proxymanager tailscale=default
9:12AM INF Generating TLS certificate Hostname=jellyfin module=proxymanager tailscale=default
9:12AM INF TLS certificate generated Hostname=jellyfin module=proxymanager tailscale=default
9:12AM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
9:13AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

Question:
Is there something I'm missing in the configuration, or could the issue be elsewhere?
Thanks!
