### ISSUE TITLE
Funnel not working?

### ISSUE THREAD

**Issue by elkinjosetm** [almeidapaulopt/tsdproxy#133]
I’m trying to setup funnel on one container but I keep getting the error: 

```
"Funnel not available; \"funnel\" node attribute not set. See https://tailscale.com/s/no-funnel." 
```

But I do have “funnel” attr in my Access Controls as the funnels docs suggest.

```

"nodeAttrs": [
		{
			// Funnel policy, which lets tailnet members control Funnel
			// for their own devices.
			// Learn more at https://tailscale.com/kb/1223/tailscale-funnel/
			"target": ["autogroup:member"],
			"attr":   ["funnel"],
		},
	],

```

Any idea why that might be happening?

**Expected behavior**

**Send config**
```

defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
        defaultproxyprovider: default
files: {}
tailscale:
    providers:
        default:
            authkey: tskey-auth-xxxxxxxxxxxxx
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```

**Logs**
```
4:49PM ERR Error Listening on TLS error="Funnel not available; \"funnel\" node attribute not set. See https://tailscale.com/s/no-funnel." module=proxymanager proxyname=plex
4:49PM INF stopping proxy module=proxymanager name=plex proxyname=plex
4:49PM INF proxy stopped module=proxymanager name=plex proxyname=plex
```
