### ISSUE TITLE
Letsencrypt showing 500 error

### ISSUE THREAD

**Issue by theshoehorn** [almeidapaulopt/tsdproxy#134]
**Before file a bug**
Do not see this in the existing issues

**Describe the bug**
When attempting to generate a TLS certificate for a DNS server container, I get the following error (below in logs section) in the compose logs, no cert is generated, and the tailscale host expires.

**Expected behavior**
A TLS cert is requested and assigned properly.

**Send config**
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.16.0.3
        defaultproxyprovider: default
#file: {}
tailscale:
    providers:
        default:
            authkey: tskey-auth-xxxxxxx
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```
**Logs**
```
tailscale-docker-proxy  | 6:27PM ERR Error starting proxy error="500 Internal Server Error: acme.GetReg: Get \"https://acme-v02.api.letsencrypt.org/directory\": dial tcp: lookup acme-v02.api.letsencrypt.org: i/o timeout" module=proxymanager proxyname=dns05
tailscale-docker-proxy  | 6:27PM INF stopping proxy module=proxymanager name=dns05 proxyname=dns05
tailscale-docker-proxy  | 6:27PM ERR tailscale.watchStatus error="Get \"http://local-tailscaled.sock/localapi/v0/status\": use of closed network connection" Hostname=dns05 module=proxymanager tailscale=default
```
**Additional context**
All other containers are successful.
