### ISSUE TITLE
Clarify docs to say that swarm is not a requirement to Docker secrets

### ISSUE THREAD

**Issue by e13h** [almeidapaulopt/tsdproxy#143]
Currently the docs say that Docker Swarm is required in order to use Docker secrets.

https://github.com/almeidapaulopt/tsdproxy/blob/5d42449acb9f05c396ebc79d5b6dfe5f1bd6825c/docs/content/docs/advanced/docker-secrets.md?plain=1#L10-L17

It is true that the [`docker secret`](https://docs.docker.com/reference/cli/docker/secret/) command is used to manage Docker Swarm secrets, but you can still use the [top-level `secrets` element](https://docs.docker.com/reference/compose-file/secrets/) in Docker Compose without using Docker Swarm. See https://docs.docker.com/compose/how-tos/use-secrets/.

For example, I could create a file named `.env` that contains my Tailscale authkey
```env
TS_AUTHKEY="Your Tailscale AuthKey"
```

Since [Docker Compose automatically interpolates variables in a `.env` file](https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#ways-to-set-variables-with-interpolation), I could then use that variable as a secret. No Docker Swarm needed.
```yaml
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - <PATH TO CONFIG>:/config
    secrets:
      - authkey

volumes:
  datadir:

secrets:
  authkey:
    environment: TS_AUTHKEY
#   ^^^^^^^^^^^ this is the important difference
```
