### ISSUE TITLE
Clarifying Direction for Multi-Port & HTTP Support

### ISSUE THREAD

**Issue by oneingan** [almeidapaulopt/tsdproxy#152]
Hi @almeidapaulopt and everyone,

I noticed multiple open issues referencing the need for:
- Hosting multiple ports (#49),
- Optional HTTP instead of forced HTTPS (#91),
- Explicit HTTP proxy support (#40).

We’d like to confirm if a single, more comprehensive approach is desirable—for example, adding a robust “entrypoints” concept to handle multiple ports and toggling between HTTP/HTTPS—or if these changes should be introduced incrementally (e.g., a simpler toggle to disable redirection and support an HTTP listener).

**Key points / questions:**
1. **Multiple Ports**: Some users need to expose more than one port or protocol simultaneously.
2. **HTTP vs. HTTPS**: Not all environments require TLS, or it may complicate certain Docker/Tailscale use cases.
3. **Proposed Approaches**:
   - A **minimal** approach: basic config toggles (`httpPort`, `httpsPort`, optional redirect) to avoid always binding :80→:443.
   - A **full** “entrypoints” system, letting each port be declared with unique settings (like scheme, address, redirection rules).

Could you share how you’d like to see this evolve? Would merging these features into a single PR/roadmap make sense, or should we keep them separate with smaller incremental changes?

Thanks in advance for your guidance!

**Comment by oneingan** [comment]
A proposed config interface for the current default config (443 TLS only entrypoint)

```yaml
defaultProxyProvider: default

docker:
  local:
    host: unix:///var/run/docker.sock
    targetHostname: 172.31.0.1
    defaultProxyProvider: default

tailscale:
  providers:
    default:
      authKey: ""
      authKeyFile: ""
      controlUrl: https://controlplane.tailscale.com
      tls: {}
      entryPoints:
        - "websecure"
  dataDir: /data/

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
```
