### ISSUE TITLE
Clearer documentation/examples for Scenarios and tsdproxy.yaml config

### ISSUE THREAD

**Issue by tootbrute** [almeidapaulopt/tsdproxy#155]
**Is your feature request related to a problem? Please describe.**
Yes. I have been self-hosting for 5 years with Yunohost but am no Docker expert. I am trying to run the scenario [1 Tsdproxy + 2 Docker servers + 1 Tailscale account](https://almeidapaulopt.github.io/tsdproxy/docs/scenarios/1i-2docker-1tailscale/).

This is a common scenario I think because I have lots of things I trust to run on my VPS but other things I want on my local server (Immich, Nextcloud, paperless etc).

I have tried editing the tsdproxy.yaml but I don't know how to link to my local server. I messed up my config a lot so I had to roll back to only Tsdproxy on VPS for now.

**Describe the solution you'd like**
More examples of the tsdproxy.yml for each scenario.

- What commands to run to get the Docker IP address?
- What is the 'port'?
- Do you need to change the daemon port?

```
docker:
  srv1: 
    host: unix:///var/run/docker.sock
    defaultProxyProvider: default
  srv2: 
    host: tcp://174.17.0.1:2376
    targetHostname: 174.17.0.1
    defaultProxyProvider: default
```
For example, I have tried different things in the srv2 part but I am just shooting in the dark. I checked `ip a` and I have so, so many things in there because I have many docker containers running. I don't use portainer or anything to mess with the containers. I just run docker compose files.

I tried my local Tailscale IP here, I tried the ip address that `ip a` shows for docker0. I don't know what port to use though.

**Describe alternatives you've considered**
I tried doing the 2 Tsdproxy, 2 docker, 1 tailscale scenario but I want all the docker containers to be on one Dashboard. I don't think that is a feature.

**Additional context**
None.
