### ISSUE TITLE
MultiPorts: ProxyList yaml configuration changes/additions

### ISSUE THREAD

**Issue by almeidapaulopt** [almeidapaulopt/tsdproxy#161]
These is my proposal to yaml port config in proxy lists:
## Syntax
```
ports:
   "<destination port>/<destination protocol>:
```
## example
```
ports:

#port 443 with https protocol proxies http://192.168.1.1:8080
  "443/https":  
    targets: 
      - "http://192.168.1.1:8080" 

#port 8880 with http protocol proxies https://192.168.1.1:8081 and don't validate target tls certificate   
  "8880/http":  
    targets: 
      - "https://192.168.1.1:8081" 
# redirect port 80 with http protocol to https://site.funny-name.ts.net
  "80/http":
    isRedirect: true
    tlsValidate: false
    targets:
      - "https://site.funny-name.ts.net"


All configuration options:
proxyname:
  proxyprovider: "default"
  dashboard:
    label: "me"
    icon: "si/docker"
    visible: true
  tailscale:
    authKey: "dddd"
    ephemeral: false
    runWebClient: true
    verbose: false
  ports:
    "port:protocol":
      targets:
         -  "http://example.com"
      isRedirect: false
      tlsValidate: false
      tailscale:
        funnel: false
```
