### ISSUE TITLE
WSL2:  TLS handshake error  i/o timeout

### ISSUE THREAD

**Issue by itsallyours** [almeidapaulopt/tsdproxy#183]
### Setup
- Windows 10
- WSL2
- Tailscale added to host
- Running TSD Proxy in WSL

### Config
docker-compose.yml
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: TSDProxy
    environment:
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    networks:
      - tailscale
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tsdproxy2      
    restart: always
    
networks:
  tailscale:  
    name: tailscale
```
tsdproxy.yaml
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        defaultproxyprovider: default
# files:
#   external:
#     filename: ""
#     defaultProxyProvider: default
#     defaultProxyAccessLog: false
tailscale:
    providers:
        default:
            authkey: ""
            authkeyfile: "/config/authkey"
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true

```

### Observations
TSD Proxy will start up and register tsdproxy2.funny-name.ts.net correctly

This command works everywhere 
```
curl http://tsdproxy2.funny-name.ts.net
<a href="https://tsdproxy2.funny-name.ts.net/">Moved Permanently</a>.
```
Now changing to https, it will fail everywhere (in WSL, host, another ts host)
```
curl https://tsdproxy2.funny-name.ts.net
curl: (28) SSL/TLS connection timeout
```
Same behavior with sample-nginx

All certs have been downloaded.

### Logs
```
Starting 1a55ab821948_TSDProxy ... done
Attaching to 1a55ab821948_TSDProxy
1a55ab821948_TSDProxy | Initializing server
1a55ab821948_TSDProxy | Version 1.4.4
1a55ab821948_TSDProxy | loading configuration from: /config/tsdproxy.yaml
1a55ab821948_TSDProxy | Validating configuration...
1a55ab821948_TSDProxy | Setting up logger
1a55ab821948_TSDProxy | 3:51AM INF Log Settings Log level=info
1a55ab821948_TSDProxy | 3:51AM INF Starting server Version=1.4.4
1a55ab821948_TSDProxy | 3:51AM INF Initializing WebServer
1a55ab821948_TSDProxy | 3:51AM INF Health check set to ready
1a55ab821948_TSDProxy | 3:51AM INF Setting up proxy proxies
1a55ab821948_TSDProxy | 3:51AM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
1a55ab821948_TSDProxy | 3:51AM INF Container a0d1abc281990e1c130b3796009b266cabaf26cce14f14d43c9cd5e6abedffff started docker=local module=proxymanager
1a55ab821948_TSDProxy | 3:51AM INF Container 1a55ab821948333b30047812a9986b0b74f47fd6fb447790744ab9705b7fce8d started docker=local module=proxymanager
1a55ab821948_TSDProxy | 3:51AM INF setting up proxy hostname=tsdproxy2 module=proxymanager proxyname=tsdproxy2
1a55ab821948_TSDProxy | 3:51AM INF starting proxy module=proxymanager name=tsdproxy2 proxyname=tsdproxy2
1a55ab821948_TSDProxy | 3:51AM INF tsnet running state path /data/default/tsdproxy2/tailscaled.state Hostname=tsdproxy2 module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF tsnet starting with hostname "tsdproxy2", varRoot "/data/default/tsdproxy2" Hostname=tsdproxy2 module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=tsdproxy2 module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF Trying to auto detect target URL container=/sample-nginx docker=local module=proxymanager try=0
1a55ab821948_TSDProxy | 3:51AM INF Successfully connected using docker network gateway and exposed port address=172.17.0.1 container=/sample-nginx docker=local module=proxymanager port=8111
1a55ab821948_TSDProxy | 3:51AM INF setting up proxy hostname=sample-nginx module=proxymanager proxyname=sample-nginx
1a55ab821948_TSDProxy | 3:51AM INF starting proxy module=proxymanager name=sample-nginx proxyname=sample-nginx
1a55ab821948_TSDProxy | 3:51AM INF tsnet running state path /data/default/sample-nginx/tailscaled.state Hostname=sample-nginx module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF tsnet starting with hostname "sample-nginx", varRoot "/data/default/sample-nginx" Hostname=sample-nginx module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF Authkey is set; but state is NoState. Ignoring authkey. Re-run with TSNET_FORCE_LOGIN=1 to force use of authkey. Hostname=sample-nginx module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF AuthLoop: state is Running; done Hostname=sample-nginx module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:51AM INF AuthLoop: state is Running; done Hostname=tsdproxy2 module=proxymanager tailscale=default
1a55ab821948_TSDProxy | 3:52AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
1a55ab821948_TSDProxy | 2025/01/30 03:53:07 http: TLS handshake error from 100.88.217.2:61771: read tcp 100.113.166.20:443->100.88.217.2:61771: i/o timeout
```
