### ISSUE TITLE
Can't connect to container using `network_mode: "service:gluetun"`

### ISSUE THREAD

**Issue by chrisbanes** [almeidapaulopt/tsdproxy#186]
**Describe the bug**

I use multiple Docker Compose files. In the first is `tsdproxy` using a network called `tailscale`.

```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    networks:
      - tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /foo:/data
      - /bar:/config
    restart: unless-stopped
    ports:
      - "8080:8080"

networks:
  tailscale:
    external: true
```

In the second I use gluetun, to allow services to connect outwards over a VPN:

```
services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    networks:
      vpn:
      tailscale:
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9696:9696 # prowlarr
    volumes:
      - /foo:/gluetun

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: "service:vpn"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "prowlarr"
      tsdproxy.container_port: 9696

networks:
  tailscale:
    external: true
```

Unfortunately I'm not able to connect to the any of the containers using `network_mode: "service:vpn"`. Using a Tailscale sidecar has been working fine for me previously.

**Send config**
The `tsdproxy.yaml` is very basic:

```
defaultproxyprovider: default
docker:
  local:
    host: unix:///var/run/docker.sock
tailscale:
  providers:
    default:
      authKey: "foo"
  datadir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: trace
  json: false
proxyaccesslog: true
```

**Logs**

On tsdproxy startup:
```
9:49AM DBG trying to connect to internal port container=/deluge docker=local hostname=172.31.0.1 module=proxymanager port=58946
9:49AM DBG Error connecting to internal port error="no valid target found for internal ports " container=/prowlarr docker=local module=proxymanager
9:49AM DBG trying to connect to internal port container=/prowlarr docker=local hostname=172.31.0.1 module=proxymanager port=9696
```

When trying to connect:
```
9:50AM ERR error host=prowlarr.foo-bar.ts.net method=GET module=proxymanager proxyname=prowlarr status=502 url=/
```

**Comment by MadManMcIvor** [comment]
Having this same issue as well! Sadly nothing to add, just wanted to follow the issue.

**Comment by almeidapaulopt** [comment]
Its the expected behavior of a "  network_mode: service:{name} ".

if you look at documentation https://docs.docker.com/reference/compose-file/services/#network_mode you will see " service:{name}: Gives the container access to the specified container by referring to its service name. "

I think it could work if you add tsdproxy labels on the "gluetun".

**Comment by chrisbanes** [comment]
That won't work if you have multiple containers connecting through gluetun though unfortunately, as TSD only supports 1:1 container to proxy.

**Comment by almeidapaulopt** [comment]
just help me understand, why you want to use tsdproxy with container in gluetun?
you use tsdproxy and is already in tailscale vpn.

**Comment by almeidapaulopt** [comment]
Ok, that's fair.
have you looked at this?
https://github.com/qdm12/gluetun-wiki/blob/main/setup/inter-containers-networking.md

maybe it help.

**Comment by almeidapaulopt** [comment]
You can use tsdproxy in your configuration with [proxylist](https://almeidapaulopt.github.io/tsdproxy/docs/list/).

add to tsdproxy.yaml
``` 
files:
  media:
    filename: /config/media.yaml
    defaultProxyProvider: default
    defaultProxyAccessLog: false
```

create file media.yaml with
```
prowlarr:
  url: http://192.168.1.10:9696
radarr:
  url: http://192.168.1.10:7878
sonarr:
  url: http://192.168.1.10:8989 
``` 

change ip to your server IP

**Comment by crsantos** [comment]
OMG! This is amazing @almeidapaulopt and @chrisbanes .

It really works! 
I had the exact same container setup: `gluetun` + `prowlarr` and I had no way of exposing `prowlarr` because of its `network_mode: "service:vpn"`.

This sounds like a great candidate to [scenarios](https://almeidapaulopt.github.io/tsdproxy/docs/scenarios/), WDYT?

**Comment by akashivskyy** [comment]
I have an existing setup that uses Tailscale Mullvad exit nodes themselves as a sort of VPN:

```yml
services:
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      TS_USERSPACE: false
      TS_EXTRA_ARGS: --exit-node=XXX.XXX.XXX.XXX
    volumes:
      - /dev/net/tun:/dev/net/tun
  service1:
    image: ...
    depends_on: [tailscale]
    network_mode: service:tailscale
  service2:
    image: ...
    depends_on: [tailscale]
    network_mode: service:tailscale
```

Can it be converted to tsdproxy with the above approach? I read the new docs in https://github.com/almeidapaulopt/tsdproxy/pull/198, they mention using gluetun but I'm not sure how to do this when Tailscale itself is used for VPN.
