### ISSUE TITLE
TSDProxy not working with proxy file

### ISSUE THREAD

**Issue by poopledc** [almeidapaulopt/tsdproxy#192]
**Before file a bug**
verify if you case is already known in https://almeidapaulopt.github.io/tsdproxy/docs/troubleshooting/
**I did**

**Describe the bug**
TSDProxy does not create anything on my tailnet. 
I have several services that I am trying to proxy through TSDProxy as shown in https://almeidapaulopt.github.io/tsdproxy/docs/list/. None of the services are through docker. I do not see much in the logs besides needing a login state for each of the services. I am using my tailscale auth key and I have tailscale https turned OFF and I have tailnet lock turned ON. The auth key has been signed using tailscale lock sign <auth_key>.

When I try to click on the icons in the dashboard (http://localhost:8080) nothing happens.

![Image](https://github.com/user-attachments/assets/a6cb2979-70eb-401f-abbe-41153b424043)

![Image](https://github.com/user-attachments/assets/661bcc22-44fe-41d4-8c77-e53683b96f52)

**Expected behavior**
I expected to see my services appear in my tailscale account

**Send config**
tsdproxy.yaml file
```
defaultProxyProvider: default
docker:
  local: # name of the docker target provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    targetHostname: 172.31.0.1 # hostname or IP of docker server
    defaultProxyProvider: default # name of which proxy provider to use
files:
  services:
    filename: /config/services.yml
    defaultProxyProvider: default
    defaultProxyAccessLog: true
tailscale:
  providers:
    default: # name of the provider
      authKey: REDACTED # optional, define authkey here
      authKeyFile: "" # optional, use this to load authkey from file. If this is defined, Authkey is ignored
      controlUrl: https://controlplane.tailscale.com # use this to override the default control URL
  dataDir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access log
```

services.yml
```
synologynasproxy:
  url: https://192.168.1.2:5001
  tlsValidate: false
orbiproxy:
  url: https://192.168.1.1
  tlsValidate: false
omegamintproxy:
  url: https://192.168.1.3:8080
  tlsValidate: false
```

**Logs**
```
Initializing server
Version 1.4.4
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
3:42AM INF Log Settings Log level=info
3:42AM INF Starting server Version=1.4.4
3:42AM INF Setting up proxy proxies
3:42AM INF Initializing WebServer
3:42AM INF Health check set to ready
3:42AM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
3:42AM INF setting up proxy hostname=orbiproxy module=proxymanager proxyname=orbiproxy
3:42AM INF starting proxy module=proxymanager name=orbiproxy proxyname=orbiproxy
3:42AM INF setting up proxy hostname=synologynasproxy module=proxymanager proxyname=synologynasproxy
3:42AM INF starting proxy module=proxymanager name=synologynasproxy proxyname=synologynasproxy
3:42AM INF setting up proxy hostname=omegamintproxy module=proxymanager proxyname=omegamintproxy
3:42AM INF starting proxy module=proxymanager name=omegamintproxy proxyname=omegamintproxy
3:42AM INF tsnet running state path /data/default/synologynasproxy/tailscaled.state Hostname=synologynasproxy module=proxymanager tailscale=default
3:42AM INF tsnet starting with hostname "synologynasproxy", varRoot "/data/default/synologynasproxy" Hostname=synologynasproxy module=proxymanager tailscale=default
3:42AM INF tsnet running state path /data/default/omegamintproxy/tailscaled.state Hostname=omegamintproxy module=proxymanager tailscale=default
3:42AM INF tsnet running state path /data/default/orbiproxy/tailscaled.state Hostname=orbiproxy module=proxymanager tailscale=default
3:42AM INF tsnet starting with hostname "orbiproxy", varRoot "/data/default/orbiproxy" Hostname=orbiproxy module=proxymanager tailscale=default
3:42AM INF tsnet starting with hostname "omegamintproxy", varRoot "/data/default/omegamintproxy" Hostname=omegamintproxy module=proxymanager tailscale=default
3:42AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=orbiproxy module=proxymanager tailscale=default
3:42AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=synologynasproxy module=proxymanager tailscale=default
3:42AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=omegamintproxy module=proxymanager tailscale=default
```

**Additional context**
None
