### ISSUE TITLE
Panic: runtime error / Segmentation fault

### ISSUE THREAD

**Issue by DrHoneyBear** [almeidapaulopt/tsdproxy#195]
**Before file a bug**
Same as this but my Pi running raspbian Bookworm does not have a /mnt/docker filesystem

**Describe the bug**
Not sure how to describe this..
```
Starting tsdproxy_tsdproxy_1 ... done
Attaching to tsdproxy_tsdproxy_1
tsdproxy_1  | Initializing server
tsdproxy_1  | Version 1.4.4
tsdproxy_1  | loading configuration from: /config/tsdproxy.yaml
tsdproxy_1  | Validating configuration...
tsdproxy_1  | Setting up logger
tsdproxy_1  | 12:57PM INF Log Settings Log level=info
tsdproxy_1  | 12:57PM INF Starting server Version=1.4.4
tsdproxy_1  | 12:57PM INF Setting up proxy proxies
tsdproxy_1  | 12:57PM INF Initializing WebServer
tsdproxy_1  | 12:57PM INF Health check set to ready
tsdproxy_1  | 12:57PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
tsdproxy_1  | 12:57PM INF Container 5f2b90895f6d434b1d96372d832502ec0c17e2def5fe30f2478ec4edb250b74b started docker=local module=proxymanager
tsdproxy_1  | 12:57PM INF Trying to auto detect target URL container=/homeassistant docker=local module=proxymanager try=0
tsdproxy_1  | 12:57PM INF Successfully connected using docker network gateway and exposed port address=172.23.0.1 container=/homeassistant docker=local module=proxymanager port=1900
tsdproxy_1  | 12:57PM INF setting up proxy hostname=homeassistant module=proxymanager proxyname=homeassistant
tsdproxy_1  | 12:57PM INF starting proxy module=proxymanager name=homeassistant proxyname=homeassistant
tsdproxy_1  | 12:57PM INF tsnet running state path /data/default/homeassistant/tailscaled.state Hostname=homeassistant module=proxymanager tailscale=default
tsdproxy_1  | 12:57PM INF tsnet starting with hostname "homeassistant", varRoot "/data/default/homeassistant" Hostname=homeassistant module=proxymanager tailscale=default
tsdproxy_1  | 12:57PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=homeassistant module=proxymanager tailscale=default
tsdproxy_1  | 12:57PM ERR tailscale.watchStatus: backend Hostname=homeassistant module=proxymanager tailscale=default
tsdproxy_1  | 12:57PM ERR Error Listening on TLS error="tsnet.Up: backend: invalid key: API key kFFG9gZL6f11CNTRL not valid" module=proxymanager proxyname=homeassistant
tsdproxy_1  | panic: runtime error: invalid memory address or nil pointer dereference
tsdproxy_1  | 	panic: runtime error: invalid memory address or nil pointer dereference
tsdproxy_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2e4b80]
tsdproxy_1  | 
tsdproxy_1  | goroutine 11 [running]:
tsdproxy_1  | net/http.(*onceCloseListener).close(...)
tsdproxy_1  | 	/opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:3775
tsdproxy_1  | sync.(*Once).doSlow(0x4000440288?, 0x400080bc30?)
tsdproxy_1  | 	/opt/hostedtoolcache/go/1.23.4/x64/src/sync/once.go:76 +0xf8
tsdproxy_1  | sync.(*Once).Do(...)
tsdproxy_1  | 	/opt/hostedtoolcache/go/1.23.4/x64/src/sync/once.go:67
tsdproxy_1  | net/http.(*onceCloseListener).Close(0x4002bb4b70)
tsdproxy_1  | 	/opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:3771 +0x4c
tsdproxy_1  | panic({0xbdc620?, 0x2e058c0?})
tsdproxy_1  | 	/opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:785 +0x124
tsdproxy_1  | net/http.(*onceCloseListener).Accept(0x24f9ec8?)
tsdproxy_1  | 	<autogenerated>:1 +0x28
tsdproxy_1  | net/http.(*Server).Serve(0x40004401e0, {0x0, 0x0})
tsdproxy_1  | 	/opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:3330 +0x294
tsdproxy_1  | github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*Proxy).start(0x4000428300)
tsdproxy_1  | 	/home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:211 +0x1cc
tsdproxy_1  | created by github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*Proxy).Start.func1 in goroutine 10
tsdproxy_1  | 	/home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:173 +0x64
```

**Expected behavior**
Run without segmentation fault !?

**Send config**
tsdproxy.yaml
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
        #targethostname: 172.20.0.1
files: {}
tailscale:
    providers:
        default:
          authKey: <<MYKEY>>
          #controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```
docker-compose.yaml
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  datadir:

```
homeassistant docker-compose.yaml
```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    ports:
      - 8123:8123
      - 1900:1900 # SSDP uPNP
      - 5353:5353 # mDNS
      - 5683:5683 # Shelley
      #- 443:443
      - 8111:80 # for TSDProxy
    privileged: true
    labels:
      - "tsdproxy.enable=true" # For TSDProxy
```

**Logs**
Always send logs

**Additional context**
