### ISSUE TITLE
ERR while using a docker-socket-proxy and following panic and crash

### ISSUE THREAD

**Issue by tiamilani** [almeidapaulopt/tsdproxy#196]
**Before file a bug**
verify if you case is already known in https://almeidapaulopt.github.io/tsdproxy/docs/troubleshooting/

I've checked but there is nothing related.

**Describe the bug**

Using a docker socket proxy if there are no events for a certain amount of time the connection times out.
Then tsdproxy goes in panic with the following error:

`ERR Error watching Docker events error="Unexpected EOF" module=proxymanager`

Following to the error tsdproxy goes into panic with the following trace:

```
panic: send on closed channel

goroutine 53 [running]:
github.com/almeidapaulopt/tsdproxy/internal/targetproviders/docker.(*Client).WatchEvents.func1()
        /home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/docker.go:165 +0x1e0
created by github.com/almeidapaulopt/tsdproxy/internal/targetproviders/docker.(*Client).WatchEvents in goroutine 6
        /home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/docker.go:152 +0x47c
```

After that tsdproxy reboots and the cycle continues.

**Expected behavior**

The connection closes as normal behavior, a new connection should be opened and the error message should be a warning.

Please notice that this has already discussed Tecnativa/docker-socket-proxy at the following issue:
[https://github.com/Tecnativa/docker-socket-proxy/issues/21](https://github.com/Tecnativa/docker-socket-proxy/issues/21)

**Send config**
tsdproxy.yaml

```
defaultProxyProvider: default
docker:
  local:
    host: tcp://socket-proxy:2375
    defaultProxyProvider: default
tailscale:
  providers:
    default:
      authKey: ""
      authKeyFile: "/run/secrets/tsauthkey"
      controlUrl: https://controlplane.tailscale.com
  dataDir: /data/
files: {}
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access log
```

**Logs**
Full log cycle

```
Initializing server
Version 1.4.4
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
10:00PM INF Log Settings Log level=info
10:00PM INF Starting server Version=1.4.4
10:00PM INF Setting up proxy proxies
10:00PM INF Initializing WebServer
10:00PM INF Health check set to ready
10:00PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
10:01PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
10:02PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
10:03PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
10:04PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
10:04PM ERR Error watching Docker events error="unexpected EOF" module=proxymanager
panic: send on closed channel

goroutine 37 [running]:
github.com/almeidapaulopt/tsdproxy/internal/targetproviders/docker.(*Client).WatchEvents.func1()
        /home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/docker.go:165 +0x1e0
created by github.com/almeidapaulopt/tsdproxy/internal/targetproviders/docker.(*Client).WatchEvents in goroutine 10
        /home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/docker.go:152 +0x47c
Initializing server
Version 1.4.4
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
10:04PM INF Log Settings Log level=info
10:04PM INF Starting server Version=1.4.4
10:04PM INF Setting up proxy proxies
10:04PM INF Initializing WebServer
10:04PM INF Health check set to ready
10:04PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
10:05PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
10:06PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
10:07PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

**Additional context**

As mentioned before please look into: [https://github.com/Tecnativa/docker-socket-proxy/issues/21](https://github.com/Tecnativa/docker-socket-proxy/issues/21)

Also, after the reboot the devices are not recreated, a manual cleanup and reboot is necessary.
