### ISSUE TITLE
Docker Container added to Tailnet show Version "1.78.3-ERR-BuildInfo"

### ISSUE THREAD

**Issue by apiaskowski** [almeidapaulopt/tsdproxy#205]
**Before file a bug**
verify if you case is already known in https://almeidapaulopt.github.io/tsdproxy/docs/troubleshooting/

- Done

**Describe the bug**
I've created some simple docker applications, like Stirling PDF and added the following labels:

- tsdproxy.enable: "true"
- tsdproxy.name: "pdf"

The applications were added successfully to my Tailnet, using the TSD Proxy, but the Version Column in the Tailscale Dashboard shows the version `1.78.3-ERR-BuildInfo`

**Expected behavior**
Applications added to Tailscale should show the correct Tailscale version, e.g. 1.80.0

**Send config**
./docker-compose.yaml:

```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tailscale-proxy
    volumes:
      - tsdproxy-data:/data
      - ${PWD}/tsdproxy-config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=dash

  pdf-app:
    image: frooodle/s-pdf:latest
    container_name: pdf-app
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pdf"
    ports:
      - 8080:8080
    volumes:
      - pdf-config:/pdf-configs
      - pdf-storage:/usr/share/tesseract-ocr/5/tessdata
    restart: unless-stopped

  mealie-app:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie-app
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "mealie"
    ports:
      - 9000:9000
    volumes:
      - mealie-data:/app/data
    environment:
      ALLOW_SIGNUP: false
    deploy:
      resources:
        limits:
          memory: 1000M
    restart: unless-stopped

volumes:
  tsdproxy-data:
    driver: local
  pdf-config:
    driver: local
  pdf-storage:
    driver: local
```

./tsdproxy-config/tsdproxy.yaml:

```
defaultProxyProvider: default
docker:
  local:
    host: unix:///var/run/docker.sock
    defaultProxyProvider: default

tailscale:
  providers:
    default:
      authKey: "tskey-auth-abc123"
```

**Logs**
TSDProxy is not showing any usual errors or warnings during setup, but some TLS handshake errors are shown

```
tailscale-proxy  | Initializing server
tailscale-proxy  | Version 1.4.4
tailscale-proxy  | loading configuration from: /config/tsdproxy.yaml
tailscale-proxy  | Validating configuration...
tailscale-proxy  | Setting up logger
tailscale-proxy  | 1:21AM INF Log Settings Log level=info
tailscale-proxy  | 1:21AM INF Starting server Version=1.4.4
tailscale-proxy  | 1:21AM INF Setting up proxy proxies
tailscale-proxy  | 1:21AM INF Initializing WebServer
tailscale-proxy  | 1:21AM INF Health check set to ready
tailscale-proxy  | 1:21AM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
tailscale-proxy  | 1:21AM INF Container 6bb61f967c7c63dc9273ff49087679194a22143c7c8282b59f9eb84edaa845f9 started docker=local module=proxymanager
tailscale-proxy  | 1:21AM INF Container 9e2fd2aa49b4d85f9b839aae310cbc8a1abf2c569e6f6a81f0bea88bce7c05f0 started docker=local module=proxymanager
tailscale-proxy  | 1:21AM INF Trying to auto detect target URL container=/pdf-app docker=local module=proxymanager try=0
tailscale-proxy  | 1:21AM INF Successfully connected using docker network gateway and exposed port address=172.18.0.1 container=/pdf-app docker=local module=proxymanager port=8080
tailscale-proxy  | 1:21AM INF setting up proxy hostname=dash module=proxymanager proxyname=dash
tailscale-proxy  | 1:21AM INF starting proxy module=proxymanager name=dash proxyname=dash
tailscale-proxy  | 1:21AM INF setting up proxy hostname=pdf module=proxymanager proxyname=pdf
tailscale-proxy  | 1:21AM INF starting proxy module=proxymanager name=pdf proxyname=pdf
tailscale-proxy  | 1:21AM INF tsnet running state path /data/default/pdf/tailscaled.state Hostname=pdf module=proxymanager tailscale=default
tailscale-proxy  | 1:21AM INF tsnet running state path /data/default/dash/tailscaled.state Hostname=dash module=proxymanager tailscale=default
tailscale-proxy  | 1:21AM INF tsnet starting with hostname "dash", varRoot "/data/default/dash" Hostname=dash module=proxymanager tailscale=default
tailscale-proxy  | 1:21AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=dash module=proxymanager tailscale=default
tailscale-proxy  | 1:21AM INF tsnet starting with hostname "pdf", varRoot "/data/default/pdf" Hostname=pdf module=proxymanager tailscale=default
tailscale-proxy  | 1:21AM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=pdf module=proxymanager tailscale=default
tailscale-proxy  | 1:22AM INF AuthLoop: state is Running; done Hostname=dash module=proxymanager tailscale=default
tailscale-proxy  | 1:22AM INF AuthLoop: state is Running; done Hostname=pdf module=proxymanager tailscale=default
tailscale-proxy  | 1:22AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
pdf-app          | Copying original files without overwriting existing files

...

tailscale-proxy  | 2025/02/20 01:23:37 http: TLS handshake error from 100.66.58.102:64516: write tcp 100.123.59.89:443->100.66.58.102:64516: i/o timeout
tailscale-proxy  | 2025/02/20 01:23:38 http: TLS handshake error from 100.66.58.102:64552: EOF
tailscale-proxy  | 2025/02/20 01:23:38 http: TLS handshake error from 100.66.58.102:64556: EOF

...
```

**Additional context**
I've tried this in a couple of different configurations, like TSDProxy and applications are hosted on the same server or separated server, as well as different tsdproxy.yaml configs, without success.
