### ISSUE TITLE
TSDProxy Doesnt Seem To Route To Nginx Container

### ISSUE THREAD

**Issue by y0utubeperson1** [almeidapaulopt/tsdproxy#213]
_The full example is here: https://github.com/y0utubeperson1/tds_test_

When attempting to route TSDProxy to nginx container, similar to how the example was given, my config doesnt seem to pick up on the nginx container and im not sure why. Im trying to use nginx as a proxy to my other containers

This is my `docker_compose.yaml` file:
```
  nginx_router:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_router
    hostname: nginx_router
    environment:
      - MY_DOMAIN=localhost
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=nginx_router
      - tsdproxy.container_port=80
    restart: unless-stopped

  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tsdproxy/data:/data
      - ./tsdproxy/config:/config
    restart: unless-stopped
    ports:
      - "8080:8080"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tds_proxy
```

And this is my tsdproxy config file:
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
files: {}
tailscale:
    providers:
        default:
            authKey: "<KEY HERE>"
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 80
log:
    level: info
    json: false
proxyaccesslog: true
```

For some reason, it always shows that connection has been refused
```
INF Log Settings Log level=info
INF Starting server Version=1.4.4
INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=tsdproxy_container module=proxymanager tailscale=default
INF Container ddddeeeeffffggggg started docker=local module=proxymanager
INF Trying to auto detect target URL container=/nginx_router docker=local module=proxymanager try=0
INF AuthLoop: state is Running; done Hostname=tsdproxy_container module=proxymanager tailscale=default
INF Trying to auto detect target URL container=/nginx_router docker=local module=proxymanager try=1
INF Trying to auto detect target URL container=/nginx_router docker=local module=proxymanager try=2
INF Trying to auto detect target URL container=/nginx_router docker=local module=proxymanager try=3
INF Trying to auto detect target URL container=/nginx_router docker=local module=proxymanager try=4
INF setting up proxy hostname=nginx_router module=proxymanager proxyname=nginx_router
INF starting proxy module=proxymanager name=nginx_router proxyname=nginx_router
INF tsnet running state path /data/default/nginx_router/tailscaled.state Hostname=nginx_router module=proxymanager tailscale=default
INF tsnet starting with hostname "nginx_router", varRoot "/data/default/nginx_router" Hostname=nginx_router module=proxymanager tailscale=default
INF LocalBackend state is NeedsLogin; running StartLoginInteractive... Hostname=nginx_router module=proxymanager tailscale=default
INF AuthLoop: state is Running; done Hostname=nginx_router module=proxymanager tailscale=default
Initializing server
Version 1.4.4
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
http: TLS handshake error from 100.107.124.121:55515: write tcp 100.115.206.76:443->100.107.124.121:55515: i/o timeout
http: TLS handshake error from 100.107.124.121:55514: write tcp 100.115.206.76:443->100.107.124.121:55514: i/o timeout
http: TLS handshake error from 100.107.124.121:55521: write tcp 100.115.206.76:443->100.107.124.121:55521: i/o timeout
http: proxy error: dial tcp 172.31.0.1:80: connect: connection refused
ERR error host=nginx_router.somesundomain.ts.net method=GET module=proxymanager proxyname=nginx_router status=502 url=/
```
