### ISSUE TITLE
network_mode: "host" and v2 does not seem to work

### ISSUE THREAD

**Issue by rmonk** [almeidapaulopt/tsdproxy#235]
**Describe the bug**
I recently migrated from v1 to v2 (hooray, multi port!) but I am having issues with two containers that use network_mode: host .  All other containers on the same host proxy perfectly through tsdproxy.

These two require direct network access for network infra purposes so I can't easily switch the network mode.  It seems that the detection routine is confused by host mode and even if I put in a "fake" ports: section it cannot see it and cannot enable the proxy.

I realize that the ports are "already exposed" but I'd like to be able to provide a simple HTTPS endpoint and share _that_ through TS instead of the unencrypted one.  I can then also enable a firewall to block non-proxied connections to secure the ports of these containers and still let them do "low level" network things like ARP scans and MDNS traffic.

I tried setting it up as a redirect but it just tells me no ports configured even with a ports section.

**Expected behavior**
tsdproxy understands host mode and proxies appropriately.

**Send config**
```
defaultProxyProvider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targetHostname: <REDACTED>
        defaultProxyProvider: default
tailscale:
    providers:
        default:
            authKey: "<REDACTED>"
            controlUrl: https://controlplane.tailscale.com
    dataDir: /data/
http:
    hostname: 0.0.0.0
    port: 8090
log:
    level: info
    json: false
proxyAccessLog: true
```

**Logs**
```
11:08AM INF stopping proxy module=proxymanager name=watchyourlan proxyname=watchyourlan
11:08AM INF proxy stopped module=proxymanager name=watchyourlan proxyname=watchyourlan
11:08AM ERR error generating target error="no port found in container" container=/watchyourlan-wyl-1 docker=local module=proxymanager port=tsdproxy.port.1
```

**Other**
Relevant compose section:
```
services:
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: always
    volumes:
    - data:/data/WatchYourLAN
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "watchyourlan"
      tsdproxy.port.1: "443/https:8840/http,no_autodetect"
```

**Comment by castorinop** [comment]
same problem. but i think is related with ports undeclared.

Expected: map ports without need defined into compose. 
maybe can get from exposedports in the manifest 

compose
```
services:
  webui:
    image: ghcr.io/open-webui/open-webui:main #v0.3.16
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "gpt"
      tsdproxy.port.1: "80/http:8080/http,no_autodetect"
```



trace
```
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:168 > getPorts container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:209 > generateTargetFromFirstTarget container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:256 > getTargetURL container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:298 > getPublishedPort container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:307 > End getPublishedPort container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:290 > End getTargetURL container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:217 > End generateTargetFromFirstTarget container=/gpt-webui-1 docker=local module=proxymanager
tsdproxy-1  | 7:27PM ERR home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:200 > error generating target error="no port found in container" container=/gpt-webui-1 docker=local module=proxymanager port=tsdproxy.port.1
tsdproxy-1  | 7:27PM TRC home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:205 > End getPorts container=/gpt-webui-1 docker=local module=proxymanager

```
