### ISSUE TITLE
Unable to connect to Minecraft Server [ROOTLESS]

### ISSUE THREAD

**Issue by Dashyyy** [almeidapaulopt/tsdproxy#252]
**Before file a bug**
verify if you case is already known in https://almeidapaulopt.github.io/tsdproxy/docs/troubleshooting/
- [x] Done

**Describe the bug**
I am not able at all to connect to a Minecraft Server I've created.
I get the Error Message `received unknown packet id 84` but it works on local LAN and if I use a tailscale sidecar container.

**Expected behavior**
I can connect to the server normally.

**Send config**
`docker-compose.yaml` for Minecraft
```yaml
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    networks:
      - tsdproxy_default
    volumes:
      - "./data:/data"
    cap_add:
      - net_raw
    labels:
      tsdproxy.enable: "true"
      tsdproxy.tsnet_verbose: "true"
      tsdproxy.port.1: "25565/tcp:25565/tcp"
# ...
networks:
  tsdproxy_default:
    external: true
```
`tsdproxy.yaml`: TsdProxy config file
```yaml 
defaultProxyProvider: default
docker:
  local:
    defaultProxyProvider: default # Required for Dashboard to work
lists:
  media:
    filename: /config/list.yaml
tailscale:
  providers:
    default:
      tags: "tag:server"
```
I've also tried it with lists:
```yaml
mc:
  ports:
    25565/tcp:
      targets:
        - tcp://mc-server:25565
```
Other things I've tried include:
- Not using the port number in lists e.g `tcp://mc-server`
- using different combinations of https, http & tcp (probably wrong)
- using autodetect (doesn't work at all probably due to rootless)
- adding `no_tlsvalidate` for list and docker
- adding udp to list with tcp
- disabling auto pause

**Logs**
I can provide them later, but some things I noticed:
- tls error when using https and http, as expected
- No logs at all when just using tcp

**Additional context**
Works on LAN, works with Tailscale Sidecar Container

### The working tailscale sidecar config:
```yaml
services:
  tailscale-client:
    image: tailscale/tailscale:latest
    container_name: tailscale-minecraft
    hostname: minecraft # This name will be the one on the tailscale network
    environment:
      TS_AUTHKEY: "tskey-auth-I-actually-almost-forgot-to-remove-it"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_USERSPACE: "FALSE" # If not using Auto-pause it can be set as true
    volumes:
      - ./ts-minecraft/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
    restart: unless-stopped
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: container:tailscale-minecraft
    volumes:
      - "./data:/data"
    cap_add:
      - net_raw
```
#### Rootless docker as the cause?
Maybe the reason is my rootless docker setup, in that case it would be appreciated to have a section in the docs dedicated to specific options that I need in order for rootless to work always.
I got Nextcloud AIO to work with rootless docker + tsdproxy, so it's not broken or something.
I haven't tried but maybe adding options to cap_add such as `net_admin` will help.
