### ISSUE TITLE
Ability to use OAuth credentials securely in v2

### ISSUE THREAD

**Issue by bennettrogers** [almeidapaulopt/tsdproxy#256]
I prefer using OAuth credentials for authenticating new machines, since as multiple issues mention it avoids the problem of having to renew the key every 90 days. I see that v2 supports clientId and clientSecret in the tsdproxy.yaml file. Is there an option to supply these variables via environment variables or a secrets file, so they can be kept out of version control?

**Comment by DadiBit** [comment]
I was wondering the same thing. Apparently the Environment variables are not available anymore (?) according to [these docs](https://almeidapaulopt.github.io/tsdproxy/docs/v2/serverconfig/)

> Environment variable configurations used in versions prior to v0.6.0 are deprecated and will be removed in future releases.

Which is a pity, since one could use the builtin `secret` option of podman/kubernetes/etc.

**Comment by pdevito3** [comment]
Yeah, this feels like a blocker to me. Seems like there is an attempt around this with docker secrets, but this would add so much more complexity than just adding a couple env vars. Very unfortunate 😕 

cc @almeidapaulopt for visibility if you're looking for beta feedback 

I'd shoot for something like this if it helps:
```yaml
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /vol1/docker/tsdproxy:/data
    environment:
      - TSDPROXY_HOSTNAME=111.111.1.11
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TSDPROXY_TAILSCALE_PROVIDERS_DEFAULT_CLIENTID=${TS_CLIENTID}
      - TSDPROXY_TAILSCALE_PROVIDERS_DEFAULT_CLIENTSECRET=${TS_SECRET}
    restart: unless-stopped
    networks:
      - tsdproxy
```

**Comment by pdevito3** [comment]
⬆️ FYI, i'm using this fork currently and it's working fine with oauth in case anyone is interested.

```yaml
  # Example: Using tsdproxy to expose Docker services on your Tailnet                                                                                                                                        
  # tsdproxy auto-discovers containers with tsdproxy labels and creates                                                                                                                                      
  # Tailscale nodes that reverse-proxy to the container's ports.                                                                                                                                             
  #                                                                                                                                                                                                          
  # Prerequisites:                                                                                                                                                                                           
  #   1. Create a Tailscale OAuth client at https://login.tailscale.com/admin/settings/oauth                                                                                                                 
  #      with "Devices: Write" scope                                                                                                                                                                         
  #   2. Create an ACL tag (e.g. tag:container) and grant the OAuth client access to it                                                                                                                      
  #   3. Set TS_OAUTH_CLIENT_ID and TS_OAUTH_CLIENT_SECRET in your environment / .env                                                                                                                        

  services:
    tsdproxy:
      image: ghcr.io/pdevito3/tsdproxy:latest
      container_name: tsdproxy
      environment:
        - TSDPROXY_TAILSCALE_PROVIDERS_DEFAULT_CLIENTID=${TS_OAUTH_CLIENT_ID}
        - TSDPROXY_TAILSCALE_PROVIDERS_DEFAULT_CLIENTSECRET=${TS_OAUTH_CLIENT_SECRET}
        - TSDPROXY_TAILSCALE_PROVIDERS_DEFAULT_TAGS=tag:container
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - tsdproxy-data:/data
      ports:
        - 8080:8080
      restart: unless-stopped
      networks:
        - tsdproxy

    # Example service: any container with tsdproxy labels gets a Tailscale hostname.
    # This creates "library.your-tailnet.ts.net" pointing to this container's port 80.
    audiobookshelf:
      image: advplyr/audiobookshelf:latest
      labels:
        tsdproxy.enable: "true"
        tsdproxy.name: "library"
      volumes:
        - ./config:/config
        - ./audiobooks:/audiobooks
        - ./metadata:/metadata
      restart: unless-stopped
      networks:
        - tsdproxy

  volumes:
    tsdproxy-data:

  networks:
    tsdproxy:
      driver: bridge

```

  Key points for anyone using this:

  - Both containers must share a network so tsdproxy can reach the backend via Docker's internal DNS/IP
  - tsdproxy.name becomes the Tailscale hostname (e.g. library.your-tailnet.ts.net)
  - No ports needed on the service if you only access it via Tailscale — the published port mapping is only needed for local/LAN access
  - /data volume is important — it persists the Tailscale node state so you don't re-register on every restart
  - The OAuth client needs the "Devices: Write" scope and access to whichever ACL tag you specify
