### ISSUE TITLE
No containers are shown in dashboard (v1)

### ISSUE THREAD

**Issue by UtkarshVerma** [almeidapaulopt/tsdproxy#267]
**Describe the bug**
`tsdproxy` does not seem to work for me at all. I use the latest v1 of this software with Podman. The container gets spawned without any errors but opening the dashboard does not show any containers.

**Expected behavior**
Dashboard should show running containers.

**Send config**
```yaml
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
files: {}
tailscale:
    providers:
        default:
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```

**Logs**
```
[+] Running 2/0
 ✔ Container dullahan-nginx-1  Created                                                                                                                               0.0s
 ✔ Container tsdproxy          Created                                                                                                                               0.0s
Attaching to nginx-1, tsdproxy
nginx-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
nginx-1   | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: using the "epoll" event method
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: nginx/1.27.5
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14)
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: OS: Linux 6.6.88
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: start worker processes
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: start worker process 17
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: start worker process 18
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: start worker process 19
nginx-1   | 2025/05/03 00:42:40 [notice] 1#1: start worker process 20
tsdproxy  | Initializing server
tsdproxy  | Version 1.4.7
tsdproxy  | loading configuration from: /config/tsdproxy.yaml
tsdproxy  | Generating default configuration to: /config/tsdproxy.yaml
tsdproxy  | 12:42AM INF Log Settings Log level=info
tsdproxy  | Validating configuration...
tsdproxy  | Setting up logger
tsdproxy  | 12:42AM INF Starting server Version=1.4.7
tsdproxy  | 12:42AM INF Setting up proxy proxies
tsdproxy  | 12:42AM INF Initializing WebServer
tsdproxy  | 12:42AM INF Health check set to ready
tsdproxy  | 12:43AM INF request host=192.168.0.2:8080 method=GET status=304 url=/
tsdproxy  | 12:43AM INF request host=192.168.0.2:8080 method=GET status=304 url=/index.js
tsdproxy  | 12:43AM INF request host=192.168.0.2:8080 method=GET status=304 url=/index.css
tsdproxy  | 12:43AM INF request host=192.168.0.2:8080 method=GET status=200 url=/r/list
tsdproxy  | 12:43AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
tsdproxy  | 12:44AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
tsdproxy  | 12:45AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
tsdproxy  | 12:46AM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

**Additional context**
Here is the `compose.yaml` I used:

```yaml
services:
  tsdproxy:
    container_name: tsdproxy
    image: docker.io/almeidapaulopt/tsdproxy:1

    networks:
      - tsdproxy

    ports:
      - 8080:8080

    environment:
      # This is required for podman for some reason:
      # https://github.com/almeidapaulopt/tsdproxy/issues/33
      STATE_DIRECTORY: /data

    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
      - ./state:/data:rw
      - ./config:/config:rw

    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - 8111:80
    networks:
      - tsdproxy
    labels:
      tsdproxy.enable: true


networks:
  tsdproxy:
    name: tsdproxy
    driver: bridge
```
