### ISSUE TITLE
HTTP Proxy to docker container not working

### ISSUE THREAD

**Issue by thebearmayor** [almeidapaulopt/tsdproxy#281]
**Before file a bug**
verify if you case is already known in https://almeidapaulopt.github.io/tsdproxy/docs/troubleshooting/

**Describe the bug**
In v2 of tsdproxy, an HTTP proxy is not working for docker container. An error is logged:
> ERR home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:200 > error generating target error="no port found in container" container=/yacreaderlibrary-server docker=local module=proxymanager port=tsdproxy.port.1

Connection attempts to port 80 on the created tailscale machine time out.

Port 8080 is exposed on the container, and I can curl `http://<container ip>:8080` successfully. If I add `ports: [8080:8080]` to yacreaderlibrary-server in docker-compose.yml, tsdproxy does not log "error generating target", but connection attempts still time out.

**Expected behavior**
I want to create an HTTP to HTTP proxy for a container. I expect to be able to connect via HTTP to the tailscale machine on port 80 and proxy to port 8080 in the container.

**Send config**
tsdproxy.yaml:
```
defaultProxyProvider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targetHostname: 172.31.0.1
tailscale:
    providers:
        default:
            controlUrl: https://controlplane.tailscale.com
            authKey: <redacted>
    dataDir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: debug
    json: false
proxyAccessLog: true
```

docker-compose.yml:
```
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy-data:/data
      - tsdproxy-config:/config
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - tsdproxy.enable=true
    privileged: true

  yacreaderlibrary-server:
    container_name: yacreaderlibrary-server
    image: yacreader/yacreaderlibraryserver:latest
    environment:
      - PUID=568
      - PGID=568
      - TZ=Etc/UTC
    volumes:
      - yacreaderlibrary-server:/config
      - comicbooks:/comics
    labels:
      - traefik.enable=true
      - tsdproxy.enable=true
      - traefik.http.routers.yacreaderlibrary-server.rule=Host(`<redacted>`)
      - traefik.http.routers.yacreaderlibrary-server.entrypoints=web
      - traefik.http.routers.yacreaderlibrary-server.middlewares=public_ipwhitelist@plugin-traefik_dynamic_public_whitelist
      - tsdproxy.port.1=80/http:8080/http
    networks:
      - traefik
    restart: unless-stopped
```

**Logs**
```
tsdproxy  | 12:59PM ERR home/runner/work/tsdproxy/tsdproxy/internal/targetproviders/docker/container.go:200 > error generating target error="no port found in container" container=/yacreaderlibrary-server docker=local module=proxymanager port=tsdproxy.port.1
tsdproxy  | 12:59PM DBG home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxymanager.go:306 > Creating proxy module=proxymanager proxy=yacreaderlibrary-server
tsdproxy  | 12:59PM INF home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:47 > setting up proxy hostname=yacreaderlibrary-server module=proxymanager proxyname=yacreaderlibrary-server
tsdproxy  | 12:59PM DBG home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:50 > initializing proxy hostname=yacreaderlibrary-server module=proxymanager proxyname=yacreaderlibrary-server
tsdproxy  | 12:59PM DBG home/runner/work/tsdproxy/tsdproxy/internal/proxyproviders/tailscale/provider.go:64 > Setting up tailscale server hostname=yacreaderlibrary-server module=proxymanager tailscale=default
tsdproxy  | 12:59PM DBG home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:61 > Proxy server created successfully hostname=yacreaderlibrary-server module=proxymanager proxyname=yacreaderlibrary-server
tsdproxy  | 12:59PM INF home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:146 > starting proxy module=proxymanager proxyname=yacreaderlibrary-server
tsdproxy  | 12:59PM WRN home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:154 > No ports configured module=proxymanager proxyname=yacreaderlibrary-server
```

**Additional context**
The client (yacreader) for this service does not support TLS, so an HTTP proxy is required.
