### ISSUE TITLE
Error Listening on TLS error="Funnel not available

### ISSUE THREAD

**Issue by ddean6232** [almeidapaulopt/tsdproxy#293]
### Describe the bug
All containers start in Docker Desktop. All (9 proxied containers with funnel - Calibre is just one example of the error, all 9 were working until a reboot of the docker desktop.

**These two lines may hold the answer to the problem:**
```
8:27PM INF Authkey is set; but state is NoState. Ignoring authkey. Re-run with TSNET_FORCE_LOGIN=1 to force use of authkey. Hostname=calibre module=proxymanager tailscale=default

8:27PM ERR Error Listening on TLS error="Funnel not available; \"funnel\" node attribute not set. See https://tailscale.com/s/no-funnel." module=proxymanager proxyname=calibre
```
**The rest of the log from tsdproxy**

```
Initializing server

Version 1.4.7

loading configuration from: /config/tsdproxy.yaml

Validating configuration...

Setting up logger

8:26PM INF Log Settings Log level=info

8:26PM INF Starting server Version=1.4.7

8:26PM INF Setting up proxy proxies

8:26PM INF Initializing WebServer

8:26PM INF Health check set to ready

8:26PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager

8:26PM INF Container 5d57aa90c56ee5ddc7c10e79cbca83275bfde3330f5b568ac5783c12adc31149 started docker=local module=proxymanager

8:26PM INF Trying to auto detect target URL container=/calibre docker=local module=proxymanager try=0

8:26PM INF Trying to auto detect target URL container=/calibre docker=local module=proxymanager try=1

8:26PM INF Trying to auto detect target URL container=/calibre docker=local module=proxymanager try=2

8:27PM INF Trying to auto detect target URL container=/calibre docker=local module=proxymanager try=3

8:27PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

8:27PM INF Trying to auto detect target URL container=/calibre docker=local module=proxymanager try=4

8:27PM INF setting up proxy hostname=calibre module=proxymanager proxyname=calibre

8:27PM INF starting proxy module=proxymanager name=calibre proxyname=calibre

8:27PM INF tsnet running state path /data/default/calibre/tailscaled.state Hostname=calibre module=proxymanager tailscale=default

8:27PM INF tsnet starting with hostname "calibre", varRoot "/data/default/calibre" Hostname=calibre module=proxymanager tailscale=default

8:27PM INF Authkey is set; but state is NoState. Ignoring authkey. Re-run with TSNET_FORCE_LOGIN=1 to force use of authkey. Hostname=calibre module=proxymanager tailscale=default

8:27PM ERR Error Listening on TLS error="Funnel not available; \"funnel\" node attribute not set. See https://tailscale.com/s/no-funnel." module=proxymanager proxyname=calibre

panic: runtime error: invalid memory address or nil pointer dereference

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6e8e07]

goroutine 103 [running]:

net/http.(*onceCloseListener).close(...)

	/opt/hostedtoolcache/go/1.24.1/x64/src/net/http/server.go:3924

sync.(*Once).doSlow(0xc0006123b8?, 0xc00065fc68?)

	/opt/hostedtoolcache/go/1.24.1/x64/src/sync/once.go:78 +0xab

sync.(*Once).Do(...)

	/opt/hostedtoolcache/go/1.24.1/x64/src/sync/once.go:69

net/http.(*onceCloseListener).Close(0xc00322a840)

	/opt/hostedtoolcache/go/1.24.1/x64/src/net/http/server.go:3920 +0x3b

panic({0x1125520?, 0x368d8d0?})

	/opt/hostedtoolcache/go/1.24.1/x64/src/runtime/panic.go:792 +0x132

net/http.(*onceCloseListener).Accept(0x2cd8c28?)

	<autogenerated>:1 +0x1e

net/http.(*Server).Serve(0xc000612300, {0x0, 0x0})

	/opt/hostedtoolcache/go/1.24.1/x64/src/net/http/server.go:3424 +0x30c

github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*Proxy).start(0xc000612400)

	/home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:211 +0x205

created by github.com/almeidapaulopt/tsdproxy/internal/proxymanager.(*Proxy).Start.func1 in goroutine 102

	/home/runner/work/tsdproxy/tsdproxy/internal/proxymanager/proxy.go:173 +0x5c
```

### Expected behavior
All proxied containers were funnelled and resolving

**Send config**
Never had to define a config.yaml file as it was just defaulting and all worked

*****Calibre Docker Compose file:**
```
services:

  calibre:
#    image: ghcr.io/linuxserver/calibre:version-v5.17.0
    image: ghcr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "calibre"
      tsdproxy.funnel: "true"
      tsdproxy.container_port: 8081
    volumes:
      - /mnt/e/calibre/config:/config
      - /mnt/e/calibre/books:/books
    ports:
      - 38080:8080
      - 38081:8081
    restart: unless-stopped
```

***Partial tsdproxy docker compose file:
```
services:

  ## tsdproxy
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
    environment:
      # Get AuthKey from your Tailscale account
      - TSDPROXY_AUTHKEY=tskey-auth-############################################
      # Address of docker server (access to example.com ports)
      - TSDPROXY_HOSTNAME=192.168.XXX.XXX
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

volumes:
  tsdproxydata:
```
