### ISSUE TITLE
TSDProxy does not work if there are no exposed ports

### ISSUE THREAD

**Issue by wsw70** [almeidapaulopt/tsdproxy#295]
_Note: I am filing this bug following https://github.com/almeidapaulopt/tsdproxy/discussions/263_

As I am investigating my problems with TSDproxy , I noticed that **the containers that "work" all have their ports mapped**.
The ones that do not, do not have the mapping.

Going from 

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:80
    labels:
      - tsdproxy.enable=true
      - tsdproxy.container_port=80
networks: {}
```

to (`ports:` removed)

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:80
    labels:
      - tsdproxy.enable=true
      - tsdproxy.container_port=80
networks: {}
```

breaks the connectivity.

Since TSDproxy is in discussion with the containers **at docker level** (and therefore on the docker network) I do not understand why the mapping would be needed.

Note: I tried v1 and v2, with -for v2- `tsdproxy.port: "443/https:80/http"` (I also tried `tsdproxy.port.1: "443/https:80/http"` ( with `.1`))

Here is an example from a container (Gitea) that exposes the service on 3000:

```
  gitea:
    image: gitea/gitea:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.XXX`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - tsdproxy.enable=true
      - tsdproxy.port=443/https:3000/http
    ports:
      - 52001:3000
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gitea:/data
```

The above works. If I remove the port binding, it stops working, **despite 52001 not being referenced in TSDProxy**

@MischaBoender added

> I ran into the same issue. If you don't specify the "ports" section in your compose file TSDProxy will give an error that the container has no ports. Technically it should not be necessary to expose ports on the host for a proxy to work, as it can directly connect to the container. I would expect TSDProxy to be similar to, for example, Treafik, where you configure the port the container uses only in a label and the proxy connects to it within the Docker network.
> 
> ```
> ERR error generating target error="no port found in container" container=/echo docker=local module=proxymanager port=tsdproxy.port.1
> WRN No ports configured module=proxymanager proxyname=echo
> ```
>

**Comment by pitschi** [comment]
I think that is what the "no_autodetect" might be for. But it does not seam to be recognized. I even used "expose" to see if it has something to do with the ports not being in the container configuration somehow.

**Comment by auspex** [comment]
I agree this should not be necessary. It forces me to keep a list of ports _that will never actually be used_! Traefik has no problem proxying to containers that don't expose ports (though, it may require the port to be specified in the docker labels, just as we sometimes need `tsdproxy.container_port`

**Comment by auspex** [comment]
Further investigation shows a non-working config:
```
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 15000:3000
    labels:
      - tsdproxy.enable=true
      - tsdproxy.scheme=http
      - tsdproxy.port=http/3000
```
Generates the errorL
```
2025/12/18 02:52:30 http: proxy error: dial tcp 172.31.0.1:15000: connect: connection timed out
```
Now, the actual reason it's failing is that the generated `tsdproxy.yaml` has:
```yaml
defaultProxyProvider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targetHostname: 172.31.0.1
        tryDockerInternalNetwork: false
```
and I have no network `172.31.0.1/16`! But it **is** looking for that local port (15000), even though it shouldn't need it.
