### ISSUE TITLE
Containers not showing up in dashboard for tailnet connection

### ISSUE THREAD

**Issue by dcardin** [almeidapaulopt/tsdproxy#299]
first: I have tried this with the stable 1.x and beta4 of 2.x and the results are the same, with albeit slightly different config.

**Problem**
I have a docker swarm setup with an overlay network connecting everything.
I have installed tdsproxy in the swarm as well as independently in a docker compose file.
Even if I set the properties properly, the service never shows up on the dashboard.

However, if I do a docker run with the tsdproxy.enable = true, then it does show up and routing works properly from the tail net.

**Expected behavior**
I would think it would automatically detect containers to connect my tailnet, first showing up in the dashboard.

**config**
```
defaultProxyProvider: default
docker:
  local: # name of the docker target provider
    host: unix:///var/run/docker.sock # host of the docker socket or daemon
    defaultProxyProvider: default # name of which proxy provider to use
lists:
  critical: # Name the target provider
    filename: /config/critical.yaml # file with the proxy list
    defaultProxyProvider: tailscale1 # (optional) default proxy provider
    defaultProxyAccessLog: true # (optional) Enable access logs
tailscale:
  providers:
    default: # name of the provider
      authKey: "REDACTED KEY"
      authKeyFile: "" # use this to load authkey from file. If this is defined, Authkey is ignored
      controlUrl: https://controlplane.tailscale.com # use this to override the default control URL
  dataDir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access log

```
**Logs**
8:29PM INF Log Settings Log level=info
8:29PM INF Starting server Version=2.0.0-beta4
8:29PM INF Setting up proxy proxies
8:29PM INF Initializing WebServer
8:29PM INF Health check set to ready
8:29PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
8:30PM INF request client=127.0.0.1:39444 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:31PM INF request client=127.0.0.1:36314 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
8:32PM INF request client=127.0.0.1:59932 host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
