### ISSUE TITLE
Ubuntu Server - Cant get Cockpit on Host Machine Accessible through TSDProxy

### ISSUE THREAD

**Issue by taibhse-designs** [almeidapaulopt/tsdproxy#304]
Ok I am running tsdproxy alongside a couple other docker services fine and with labels can access them through my tailscale, however, I run cockpit on my ubuntu server to be able to manage the server through a browser, but no matter what way I setup the critical.yaml file, I cant seem to get it to work through tsdproxy and on my tailscale.

Cockpit is not run in a docker container, its directly on the host machine, 

Any help to get this working would be greatly appreciated,

the following is my critical.yaml file

```
cockpit:
  url: http://192.168.1.152:9090
  proxyProvider: default
  tlsValidate: false
  tailscale:
    authKey: 123456-redacted
    ephemeral: false
    runWebClient: false
    verbose: false
    funnel: false
  dashboard:
    visible: true
```

the following is my tsdproxy.yaml file

```
defaultproxyprovider: default
docker:
  local:
    host: unix:///var/run/docker.sock
    defaultproxyprovider: default
tailscale:
  providers:
    default:
      authkey: ""
      authkeyfile: "/config/authkey"
      controlurl: https://controlplane.tailscale.com
  datadir: /data/
files:
  critical:
    filename: /config/critical.yaml
    defaultProxyProvider: tailscale1
    defaultProxyAccessLog: true
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info
  json: false
proxyaccesslog: true
```

**Comment by Zolfax** [comment]
I'm not sure whether you could switch to version 2 of TSDProxy.
I have the equivalent of what you wrote running with my NAS.

Here's my version 2 critical.yaml

```
cockpit:
  proxyProvider: default
  tailscale:
    ephemeral: false
  ports:
    80/http:
      targets:
        - http://192.168.1.152:9090
    443/https:
      targets:
        - http://192.168.1.152:9090
```

Adjustment you would need to do in your normal file: files --> lists
