### ISSUE TITLE
Getting permission denied while trying to access the docker socket

### ISSUE THREAD

**Issue by kavishgr** [almeidapaulopt/tsdproxy#44]
compose.yml:

```yaml
services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:
      - ./datadir:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEY=xxxxxx
      - TSDPROXY_HOSTNAME=192.168.100.200
      - DOCKER_HOST=unix:///var/run/docker.sock
```

I guess it has something to do with `TSDPROXY_HOSTNAME` (I'm not sure). I tried using `127.0.0.1`, `localhost`, and `host.docker.internal`, but I'm still getting a permission denied error:

```console
tailscale-docker-proxy-1  | Initializing server
tailscale-docker-proxy-1  | Version
tailscale-docker-proxy-1  | 5:34AM INF Log Settings Log level=info
tailscale-docker-proxy-1 exited with code 1
tailscale-docker-proxy-1  | 5:34AM INF Starting server Version=
tailscale-docker-proxy-1  | 5:34AM INF Setting up proxy for existing containers
tailscale-docker-proxy-1  | Setting up logger
tailscale-docker-proxy-1  | 5:34AM ERR error listing containers error="permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/containers/json?filters=%7B%22label%22%3A%7B%22tsdproxy.enable%3Dtrue%22%3Atrue%7D%7D\": dial unix /var/run/docker.sock: connect: permission denied"
tailscale-docker-proxy-1  | 5:34AM FTL Error setting up existing containers error="error listing containers: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.47/containers/json?filters=%7B%22label%22%3A%7B%22tsdproxy.enable%3Dtrue%22%3Atrue%7D%7D\": dial unix /var/run/docker.sock: connect: permission denied"
```
**Figured it out but still confused**:

I had to set `privileged: true`. Any idea why ?
