### ISSUE TITLE
404 when trying to access Jellyfin specifically

### ISSUE THREAD

**Issue by wolffshots** [almeidapaulopt/tsdproxy#45]
I have Jellyfin running in a container which looks something like this:
```
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: 144:1005 # jellyfin:mediagroup
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - ./jellyfin/config:/etc/jellyfin
      - ./jellyfin/data:/var/lib/jellyfin
      - ./jellyfin/cache:/var/cache/jellyfin
      - ./jellyfin/logs:/var/log/jellyfin
      - /media:/media
    restart: unless-stopped
    network_mode: host
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: jellyfin
      tsdproxy.container_port: 8086
```
And tsdproxy running like this:
```
services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tsdproxy/data:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEY=${AUTHKEY}
      - TSDPROXY_HOSTNAME=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
    network_mode: host
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tsdproxy
      - tsdproxy.container_port=8080
```
But when navigating to `jellyfin.<funny-name>.ts.net` I get a 404 and this log in tsdproxy `ERR error host=jellyfin.<funny-name>.ts.net method=GET status=404 url=/` and the error that I get in browser looks like this:
```
This jellyfin.<funny-name>.ts.net page can’t be found
No webpage was found for the web address: https://jellyfin.<funny-name>.ts.net/
HTTP ERROR 404
```

This is my previous config for Caddy which does work still:
```
# jellyfin
<machine>.<funny-name>.ts.net:8097 {
    reverse_proxy http://localhost:8096
}
```

Accessing the local machine IP on 8096 also works.

I have tried changing both to bridge network, one bridge one host and vice versa and it just doesn't find Jellyfin or elaborate as to why it can't. I have very similar setup for Plex and a few other containers and they work at `plex.<funny-name>.ts.net` and the likes no problem.

Anyone have any idea how to get this to work or how to investigate further?
