### ISSUE TITLE
Prevent recreation of machines

### ISSUE THREAD

**Issue by Tom7320** [almeidapaulopt/tsdproxy#53]
Hi everyone,

Last night, my server auto-updated the tsdprox container. After the container restart, tsdproxy (tried) to recreate the already existing machines. The problem with the recreation is either:

- if the auth key is already expired, creation of the machine fails or
- the machine gets a different name by adding a suffix like "-1" for example.

Therefore, I would like tsdproxy to prevent the creation of machines that already exist. Is that possible? Another solution could be the use of never expiring OAuth ephemeral nodes?!

Thx a lot for the great software! :blush:

**Comment by almeidapaulopt** [comment]
If you activate ephemeral, they will be deleted automatically.

**Comment by bronson** [comment]
I have ephemeral activated and still ended up with -1 names.  (and ephemeral is the default, right? On my tailscale dashboard, the tsdproxy machines all have the blue label)

**Comment by staticEndeavour** [comment]
Just adding my setup which currently doesn't work. Tailscale starts them up, reads the tsdproxy nodes as having 'Duplicate node keys', and then kills all but one after a few seconds. Any help greatly appreciated.

tsdproxy docker-compose.yml

```services:
  tsdproxy:
    container_name: tsdproxy
    image: almeidapaulopt/tsdproxy:1
    networks:
      - tailscale

volumes:
  datadir:

networks:
  tailscale:
    external: true
```


tsdproxy.yaml
```
defaultProxyProvider: default
docker:
    island:
        host: unix:///var/run/docker.sock
        defaultProxyProvider: default
tailscale:
    providers:
        default:
            authKey: "xxx"
    datadir: /data/

files:
    arrstack:
        filename: /config/arrstack.yaml
        defaultProxyProvider: default
        defaultProxyAccessLog: false
```


arrstack.yaml
```
huntarr: 
  url: http://huntarr:9705
lidarr: 
  url: http://lidarr:8686
nzbget: 
  url: http://nzbget:6789
pinchflat: 
  url: http://pinchflat:8945
prowlarr: 
  url: http://prowlarr:9696
qbittorrent: 
  url: http://qbittorrent:8282
radarr: 
  url: http://radarr:7878
sonarr: 
  url: http://sonarr:8989
slskd: 
  url: http://slskd:5030
```

gluetun docker-compose.yml
```
services:
  gluetun:
    # image: qmcgaw/gluetun:v3.38
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8282:8282 #qbittorrent
      ...etc
      - 8945:8945 #pinchflat
    networks:
      tailscale:
        aliases:
          - huntarr
          - lidarr
          - nzbget
          - pinchflat
          - prowlarr
          - qbittorrent
          - radarr
          - sonarr
          - slskd

networks:
  tailscale:
    external: true
```
