### ISSUE TITLE
tsdproxy 502 error

### ISSUE THREAD

**Issue by Tom7320** [almeidapaulopt/tsdproxy#54]
Hi everyone

Since the update to version 1 yesterday, tsdproxy stopped working for me. I try to access a website like nginx-test.funny-name.ts.net and get the following error message:

```
1:04PM ERR error host=nginx-test.funny-name.ts.net method=GET module=proxymanager proxyname=nginx-test status=502 url=/
2024/11/28 13:04:43 http: proxy error: dial tcp 172.29.0.2:80: i/o timeout
2024/11/28 13:04:46 http: proxy error: context canceled
```

Docker compose files:

```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/tsdproxy:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEY=tskey-auth-abc
      - TSDPROXY_HOSTNAME=192.168.205.2
      - DOCKER_HOST=unix:///var/run/docker.sock
```

```
services:
  web:
    image: nginx
    container_name: nginx-test
    ports:
      - "8080:80"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.funnel: "true"
```

I really apologize for the perhaps stupid question, but it just stopped working for me since version 1, and I can not figure out why.... 

Thx for reading and the very useful project!
