### ISSUE TITLE
autodetects the exposed port and not the tsdproxy.container_port

### ISSUE THREAD

**Issue by almeidapaulopt** [almeidapaulopt/tsdproxy#56]
> I've made a different approach with in next branch. If you want you can try using: image: almeidapaulopt/tsdproxy:next .

I tried it out with v1.0.0-rc1 and it is working for me. Thanks!

Nevertheless for example the qbittorrent service I need to specify the webui port because it autodetects the exposed port as the one to use in the proxy (57446).

```
qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      WEBUI_PORT: 8080
      TORRENTING_PORT: 57446
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /mnt/docker/config/qbittorrent:/config
      - /mnt/data/downloads:/data/downloads
      - /mnt/data/media/others:/data/downloads/others
    ports:
      - 57446:57446
      - 57446:57446/udp
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.5'
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: 8080
```

Not sure if this could be improved so it detects that the one to use is 8080 automatically.

_Originally posted by @Korveck14 in https://github.com/almeidapaulopt/tsdproxy/issues/38#issuecomment-2505664483_
