### ISSUE TITLE
error getting proxy config: error parsing target hostname: no valid target found for /jellyfin

### ISSUE THREAD

**Issue by AstroEngineeer** [almeidapaulopt/tsdproxy#61]
### TSDProxy Compose
```dockerfile
networks:
  default:
    name: ts-proxy
    external: true

services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:1.0.0-rc2
    container_name: tailscale-docker-proxy
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./container_data/tsdproxy/data:/data
      - ./container_data/tsdproxy/config:/config
    restart: unless-stopped
``` 
### TSDProxy Config
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 192.168.18.2
        defaultproxyprovider: default
file: {}
tailscale:
    providers:
        default:
            authkey: "xyz"
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: debug
    json: false
proxyaccesslog: true
``` 
### Jellyfin Compose
```dockerfile
networks:
  tk-proxy:
    name: tk-proxy
    external: true
  ts-proxy:
    name: tk-proxy
    external: true

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: 'unless-stopped'
    user: 1000:1000
    group_add:
      - '105'
    networks:
      - tk-proxy
      - ts-proxy
    volumes:
      - /mnt/void/data/media:/media
      - ./container_data/jellyfin/cache:/cache
      - ./container_data/jellyfin/config:/config
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    labels:
      # traefik enalbed
      - "traefik.enable=true"
      # traefik middleware
      - "traefik.http.middlewares.jellyfin-headers.headers.customresponseheaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.middlewares.jellyfin-headers.headers.sslredirect=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.sslforcehost=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.stsseconds=315360000"
      - "traefik.http.middlewares.jellyfin-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.stspreload=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.forcestsheader=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.framedeny=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.browserxssfilter=true"
      # traefik config
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.mydomain.tld`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-headers"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      # tailscale proxy
      - "tsdproxy.enable=true"
      - "tsdproxy.name=jellyfin"
      - "tsdproxy.container_port=8096"
      - "tsdproxy.funnel=false"
``` 
### Logs
[tailscale-docker-proxy-2024-11-30T05-42-52.log](https://github.com/user-attachments/files/17964377/tailscale-docker-proxy-2024-11-30T05-42-52.log)

What am i doing wrong here? Logs indicate that `no valid target found for exposed/internal ports` but i've added the label `tsdproxy.container_port=8096`
