### ISSUE TITLE
Referencing Environment Variables in tsdproxy.yml

### ISSUE THREAD

**Issue by JohnYangSam** [almeidapaulopt/tsdproxy#64]
When setting the tailscale authentication token, I'm trying to use a .env file which passes the key to docker compose, setting it in environment variables for the tsdproxy container and then reference it in the tsdproxy.yaml file like the below.

However, I keep getting an error that the key is incorrect.

Directly adding the key to the tsdproxy.yaml file works.

Am I trying to do something that isn't yet supported?

-----

`.env`

```
TS_AUTHKEY=<authkey>
```

`docker-compose.yaml`
```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy-data:/data
      - ${PWD}/tailscale-config:/config
    restart: unless-stopped
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
```

`config/tsdproxy.yaml`

```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1
        defaultproxyprovider: default
file: {}
tailscale:
    providers:
        default:
            authkey: ${TS_AUTHKEY}
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```

**Comment by almeidapaulopt** [comment]
Instead of a env file. 
Remove the TS_AUTHKEY=, call it for example (${PWD}/tailscale-config/authkey)

And use authkeyfile: "/config/authkey".
Set authkey:"".

**Comment by JohnYangSam** [comment]
Thanks @almeidapaulopt. Huge fan of this project!

Note for those who find this online later:

Another way to avoid needing to edit the default tsdproxy.yml configuration:

In your docker-compose.yml file, you can specify the authkey for each service using the `tsdproxy.authkey=` label and reference it in a `.env` file.

e.g.

In `.env`:

```
TAILSCALE_AUTH_KEY=your-auth-key
```

In `docker-compose.yml`:

```
services:
    nginx:
        labels:
            tsdproxy.enable: "true"
            tsdproxy.name: "tailnet name"
            tsdproxy.container_port: "8080"
            tsdproxy.ephemeral: "true"
            tsdproxy.authkey: ${TAILSCALE_AUTH_KEY}
       ...
```

See: https://almeidapaulopt.github.io/tsdproxy/docs/docker/#tsdproxyauthkey
