### ISSUE TITLE
No nodes are being added to my tailnet

### ISSUE THREAD

**Issue by lucaguarro** [almeidapaulopt/tsdproxy#65]
I am trying to use tsdproxy to access jellyfin on my tailnet. However when I do a `docker compose restart`, the containers seem to start and run without issue but when I look on my tailnet on tailscale.com, I do not see any nodes. I followed the guides and the examples in the documentation but maybe I missed something. Could someone help me debug?

This is my `compose.yaml` file:

```
---
services:

  ## tsdproxy
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    user: root
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - /home/gleb/tsdproxy:/config
    restart: unless-stopped

  ## Jellyfin
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /home/gleb/jellyfin/config:/config
      - /home/gleb/jellyfin/cache:/cache
      - /mnt/media1:/media
    labels:
      tsdproxy.enable: true
      tsdproxy.name: jellyfin
      tsdproxy.container_port: 8096
    ports:
      - 8096:8096
    restart: unless-stopped

volumes:
  datadir:
  ```
and the `tsdproxy.yaml`:
```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 172.31.0.1 
        defaultproxyprovider: default
file: {}
tailscale:
    providers:
        default:
            authkey: tskey-auth-XXXXXXXXXXXXXXXXXXXXXXX
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
```
