### ISSUE TITLE
How to properly configure jellyfin with tsdproxy?

### ISSUE THREAD

**Issue by lucaguarro** [almeidapaulopt/tsdproxy#66]
I am able to get the jellyfin node up and running in my tailnet but then when I try to access the url of that node, I am greeted with this page:
![image](https://github.com/user-attachments/assets/0b8e2a35-0fa3-4115-923f-eb8c28fabb22)

This is what my `compose.yaml` file looks like:
```
services:

  ## tsdproxy
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - /home/gleb/tsdproxy:/config
    restart: unless-stopped

  ## Jellyfin
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gleb/jellyfin/config:/config
      - /home/gleb/jellyfin/cache:/cache
      - /mnt/media1:/media
    labels:
      tsdproxy.enable: true
      tsdproxy.name: jellyfin
      tsdproxy.container_port: 8096 
    ports:
      - "8096:8096" # Web UI port
      - "8920:8920" # HTTPS port (optional)
    restart: unless-stopped

volumes:
  datadir:
```

Is there something wrong with the way I configured my ports? Unsure if I am supposed to be opening up additional ports for [automatic service discovery](https://jellyfin.org/docs/general/networking/)... Anyone able to help me? Thanks.
