### ISSUE TITLE
Some services won't be added to Tailnet

### ISSUE THREAD

**Issue by eduariasv** [almeidapaulopt/tsdproxy#70]
Some services won't be added to Tailnet, even after indicating the internal port using the `tsdproxy.container_port` flag. 

Here's the config for the server:
`defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targethostname: 192.168.XXX.XXX
        defaultproxyprovider: default
file: {}
tailscale:
    providers:
        default:
            authkey: tskey-REDACTED
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
`

I've noticed that 2 services are in the Host network, and 1 isn't. I've added the container port as a label, with no success.

**Comment by almeidapaulopt** [comment]
Send the logs

**Comment by eduariasv** [comment]
```
9:17PM INF Log Settings Log level=info
9:17PM INF Starting server Version=
9:17PM INF Setting up proxy proxies
9:17PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
9:17PM INF Trying to auto detect target URL container=/overseerr docker=local module=proxymanager try=0
9:17PM INF Trying to auto detect target URL container=/immich-server docker=local module=proxymanager try=0
9:17PM INF Successfully connected using docker network gateway and exposed port address=172.30.0.1 container=/immich-server docker=local module=proxymanager port=2283
9:17PM INF Successfully connected using docker network gateway and exposed port address=172.25.0.1 container=/overseerr docker=local module=proxymanager port=5055
9:17PM INF setting up proxy hostname=immich module=proxymanager
9:17PM INF starting proxy module=proxymanager name=immich proxyname=immich
9:17PM INF setting up proxy hostname=overseerr module=proxymanager
9:17PM INF starting proxy module=proxymanager name=overseerr proxyname=overseerr
9:17PM INF Initializing WebServer
9:17PM INF Health check set to ready
9:17PM INF tsnet running state path /data/default/immich/tailscaled.state module=proxymanager tailscale=default
9:17PM INF tsnet starting with hostname "immich", varRoot "/data/default/immich" module=proxymanager tailscale=default
9:17PM INF tsnet running state path /data/default/overseerr/tailscaled.state module=proxymanager tailscale=default
9:17PM INF tsnet starting with hostname "overseerr", varRoot "/data/default/overseerr" module=proxymanager tailscale=default
9:17PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
9:17PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
9:17PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
9:17PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
9:18PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

I don't see anything that suggests it is identifying the other containers that are not added.

**Comment by almeidapaulopt** [comment]
Sem compose files please.

**Comment by Vexz00** [comment]
@almeidapaulopt 
Same problem with three different docker containers.

Here is the compose file of one of them:
```
services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: Audiobookshelf
    network_mode: "bridge"
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 13378:80
    volumes:
      - /volume1/docker/Audiobookshelf:/config:rw
      - /volume1/docker/Audiobookshelf/audiobooks:/audiobooks:rw
      - /volume1/docker/Audiobookshelf/metadata:/metadata:rw
    environment:
      PUID: 1043
      PGID: 100
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "audiobookshelf"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: 80
    restart: no
```

For some reason this one, whenever I try to open the MagicDNS FPQN with HTTPS in my browser, it adds port `5001` at the and of the URL.
