### ISSUE TITLE
Cannot auth with tailscale using yaml config

### ISSUE THREAD

**Issue by Korveck14** [almeidapaulopt/tsdproxy#76]
I am using the following yaml config:

```
defaultproxyprovider: default
docker:
  local: # name of the docker provider
    host: unix:///var/run/docker.sock
    defaultproxyprovider: default
tailscale:
  providers:
    default:
      authkey: tskey-auth-***
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyaccesslog: true # set to true to enable container access log
```

Nevertheless I am getting the following errors in tsdproxy:
`tsdproxy       | 6:50AM ERR Error Listening on TLS error="tsnet.Up: backend: invalid key: unable to validate API key" module=proxymanager proxyname=sonarr`

While if I use the TSDPROXY_AUTHKEY variable on my docker-compose file it is totally fine. Also I am using the same key for both methods.

Can you help me out?
