### ISSUE TITLE
Error creating Docker provider error="could not find default bridge network"

### ISSUE THREAD

**Issue by joelschou** [almeidapaulopt/tsdproxy#79]
Here's my system (I realize it's fairly non-standard):

* Mac mini M2
* macOS 15.1.1
* Podman 5.3.0

My config files are pretty darn close to the stock examples:

```yaml
# compose.yaml

services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
volumes:
  datadir:
```

☝️ I had to add `privileged: true` to get past an earlier error.

👇 When I change the error level to `trace` it fails schema validation.

```yaml
# config/tsdproxy.yaml

defaultproxyprovider: default
docker:
  local: # name of the docker provider
    host: unix:///var/run/docker.sock
    defaultproxyprovider: default
tailscale:
  providers:
    default:
      authkey: tskey-auth-****
log:
  level: info # set logging level info, error or trace
  json: false # set to true to enable json logging
proxyaccesslog: true # set to true to enable container access log
```

Whenever I run compose, the logs look like this:

```
Initializing server
Version 
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
10:23PM INF Log Settings Log level=info
10:23PM INF Starting server Version=
10:23PM INF Setting up proxy proxies
10:23PM INF Initializing WebServer
10:23PM INF Health check set to ready
�10:23PM ERR Error creating Docker provider error="could not find default bridge network" module=proxymanager
10:23PM ERR No Target Providers found module=proxymanager
�10:23PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

As you can see, the `/health/ready/` endpoint pings just fine. I've tried all sorts of different configurations but cannot get past this error. 

Thanks!
