### ISSUE TITLE
Cant get it to work fully

### ISSUE THREAD

**Issue by ricostuart** [almeidapaulopt/tsdproxy#8]
This is a great idea so far! however, i have got a couple of problems so far:
1. The use of secrets. When I try and setup with a secretfile (eg authfile) i get the following error:
> error: read auth key from file: open /run/secrets/authkey: no such file or directory

```
services:
  tailscale-docker-proxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tailscale_docker_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/tsdproxy:/data
    restart: unless-stopped
    environment:
# Authkey works
#      - TSDPROXY_AUTHKEY=tskey-auth-SecretKey
# Authkeyfile not working
      - TSDPROXY_AUTHKEYFILE=/run/secrets/authkey
# Local host
      - TSDPROXY_HOSTNAME=127.0.0.1     
secrets:
  authkey:
    external: true
```

Ive also tried with:

```
secrets:
  authkey:
    file: authkey
```

But nothing works. Only way I can get it to work is if I leave the key in the main compose.yml. 

2. Whenever i have to restart the container the key is invalidated. I have changed the key I created to be multi used and that seems to work. But is there a way of using the API instead? Not sure if that would be easier for a multi-docker setup?

3. I've only started trying to setup Portainer with this proxy but i cannot get it to work at all.
My compose.yml is : 

```
services:
  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: unless-stopped
    ports:
      - "9001:9001"

  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer-ee
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    restart: unless-stopped
    ports:
      - "9443:9443"
    volumes:
      - /docker/portainer/data:/data
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "portainer-oracle1"
      tsdproxy.container_port: 9443
      tsdproxy.ephemeral: "true"
      tsdproxy.webclient: "true"
```

I have just added the ephemeral and web-client in attempts to solve a few issues (the ephemeral seems to work for when containers go up and down) but so far no joy.
This server is hosted up on Oracle Cloud (i've not started playing with my homelab setup yet), so I have tried:
```
# Private IP
#      - TSDPROXY_HOSTNAME=10.**.**.***
# Local host
      - TSDPROXY_HOSTNAME=127.0.0.1
# Public IP
#      -TSDPROXY_HOSTNAME=***.***.***.***
```
but none of the IP's used seem to work. I have got it connected correctly in Tailscale admin:
![Screenshot 2024-11-06 at 11 08 47 am](https://github.com/user-attachments/assets/acc94467-2af6-4d12-89a3-91fa3af473ec)

However, looking into the machine itself, the port 9443 to access Portainer doesn't show up:
![Screenshot 2024-11-06 at 11 11 46 am](https://github.com/user-attachments/assets/9e1769b5-767c-4d02-a774-6f26c166f80d)

I've restarted all the containers, deleted the created folder in the tsdproxy folder and restarted, etc, but nothing will get me access to Portainer. 

I do have access to it currently using cloudflare tunnels so i haven't opened up the port to the outside world (which i don't really want to do).

I'm obviously going wrong somewhere just not sure where. 

Thanks!
