### ISSUE TITLE
Traefik label with tsdproxy label

### ISSUE THREAD

**Issue by rasulovk** [almeidapaulopt/tsdproxy#81]
hi, I would like to know if it possible to use treaffik labels with tsdproxy label at same time, or please advise other solution ?
```
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - tsdproxy.enable=true
        - tsdproxy.name=pdf
        - tsdproxy.container_port=8080
        - traefik.enable=true
```
