### ISSUE TITLE
None of my new containers gets a HTTPS cert and cant connect, in seperate compose files

### ISSUE THREAD

**Issue by runerally** [almeidapaulopt/tsdproxy#83]
Hi. I don't know if I have misunderstood everything but i have have separated the docker-compose files for each deployment individually. I.e TDSproxy in one compose, gitea in another etc. Anyway TSDproxy only work when it's in the same compose file as the other services or they are on the same network as TSDproxy, (network_mode: networksameasTSDproxy). 

Here is my compose file of a separate service that doesn't work:
```
version: "3"
networks:
  gitea:
    external: false
services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: gitea
```
And here my tsdproxy inside my immich deployment that is working with immich (without the immich part):

```
name: immich-app
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir2:/data
      - ./config:/config
    restart: unless-stopped
volumes:
  datadir2: null
```
Here is the error message from the container:
```
ERR error host=gitea.funny-name.ts.net method=GET module=proxymanager proxyname=gitea status=502 url=/
ERR error host=gitea.funny-name.ts.net method=GET module=proxymanager proxyname=gitea status=502 url=/favicon.ico
``` 
My docker instance runs on a privileged Proxmox LXC that also run tailscale, intel n6005, 64gb of ram.

Im trying to simplify my homelab as much as possible with TS and found this project that would really help. Keep up the good work.

**Comment by almeidapaulopt** [comment]
please post you tsdproxy.yaml in  ./config .

Set log to "debug" e send more log context.

**Comment by runerally** [comment]
Config: I removed the targethostname just to test, before it was set to the host ip of the lxc

```
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
#        targethostname: 172.31.0.1
        defaultproxyprovider: default
file: {}
tailscale:
    providers:
        default:
            authkey: tskey-dsadafkejffjikew
            authkeyfile: ""
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: debug
    json: false
proxyaccesslog: true
```

Set to debug, only service dockge running:
```
Initializing server
Version
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
2:15PM INF Log Settings Log level=debug
2:15PM INF Starting server Version=
Setting up logger
2:15PM INF Setting up proxy proxies
2:15PM DBG Setting up Tailscale Providers module=proxymanager
2:15PM DBG Created Proxy provider module=proxymanager provider=default
2:15PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
2:15PM DBG Creating proxies for provider module=proxymanager provider=local
2:15PM INF Trying to auto detect target URL container=/dockge-dockge-1 docker=local module=proxymanager try=0
2:15PM DBG trying to connect to internal port container=/dockge-dockge-1 docker=local hostname=172.31.0.1 module=proxymanager port=5001
2:15PM INF Trying to auto detect target URL container=/gitea docker=local module=proxymanager try=0
2:15PM DBG trying to connect to internal port container=/gitea docker=local hostname=172.31.0.1 module=proxymanager port=22
2:15PM INF Successfully connected address=172.19.0.2 container=/dockge-dockge-1 docker=local module=proxymanager port=5001
2:15PM INF Successfully connected address=172.23.0.2 container=/gitea docker=local module=proxymanager port=22
2:15PM DBG Creating proxy module=proxymanager proxy=dockge
2:15PM INF setting up proxy hostname=dockge module=proxymanager
2:15PM DBG initializing proxy hostname=dockge module=proxymanager proxyURL=https://dockge targetURL=http://172.19.0.2:5001
2:15PM DBG Setting up tailscale server ephemeral=true hostname=dockge module=proxymanager runWebClient=false tailscale=default
2:15PM DBG Proxy server created successfully hostname=dockge module=proxymanager proxyname=dockge
2:15PM INF starting proxy module=proxymanager name=dockge proxyname=dockge
2:15PM DBG Creating proxy module=proxymanager proxy=gitea
2:15PM INF setting up proxy hostname=gitea module=proxymanager
2:15PM DBG initializing proxy hostname=gitea module=proxymanager proxyURL=https://gitea targetURL=http://172.23.0.2:22
2:15PM DBG Setting up tailscale server ephemeral=true hostname=gitea module=proxymanager runWebClient=false tailscale=default
2:15PM DBG Proxy server created successfully hostname=gitea module=proxymanager proxyname=gitea
2:15PM INF starting proxy module=proxymanager name=gitea proxyname=gitea
2:15PM INF Initializing WebServer
2:15PM INF Health check set to ready
2:15PM INF tsnet running state path /data/default/gitea/tailscaled.state module=proxymanager tailscale=default
2:15PM INF tsnet starting with hostname "gitea", varRoot "/data/default/gitea" module=proxymanager tailscale=default
2:15PM INF tsnet running state path /data/default/dockge/tailscaled.state module=proxymanager tailscale=default
2:15PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
2:15PM INF tsnet starting with hostname "dockge", varRoot "/data/default/dockge" module=proxymanager tailscale=default
2:15PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
2:15PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
2:15PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
2:15PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
2:16PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
2024/12/08 14:16:13 http: proxy error: dial tcp 172.19.0.2:5001: i/o timeout
2:16PM ERR error host=dockge.funny-name.ts.net method=GET module=proxymanager proxyname=dockge status=502 url=/
2024/12/08 14:16:13 http: proxy error: context canceled
2:16PM ERR error host=dockge.funny-name.ts.net method=GET module=proxymanager proxyname=dockge status=502 url=/favicon.ico
2:16PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
2:17PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
2:17PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

```
