### ISSUE TITLE
Configurable entrypoints

### ISSUE THREAD

**Issue by oneingan** [almeidapaulopt/tsdproxy#90]
I'm using `tsdproxy` to connect to multiple Docker [swarmgate](https://github.com/neuroforgede/swarmgate/) proxies. Considering the default Docker client connection parameters, I’d like to configure different ports, using Docker's defaults: `2375` (for plain HTTP) and `2376` (for HTTPS).

So, please, make them user configurable.

**Comment by oneingan** [comment]
here traefik similar config:

```yaml
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
```
