### ISSUE TITLE
When restarting container TSDProxy is not able to proxy the correct port

### ISSUE THREAD

**Issue by Korveck14** [almeidapaulopt/tsdproxy#92]
I’m encountering an issue where restarting the qBittorrent container causes TSDProxy to lose its connection and then reconnect to the wrong port, despite the correct port being specified in the docker-compose.yml.

Here’s my qBittorrent configuration:

```
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - /mnt/docker/config/qbittorrent:/config
      - /mnt/data/downloads:/data/downloads
      - /mnt/data/media/others:/data/downloads/others
    ports:
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: 8080
```

When TSDProxy starts after qBittorrent is already running, everything works as expected. The log confirms proper functionality. However, after restarting the qBittorrent container using docker-compose restart qbittorrent, TSDProxy logs show that it initially detects a connection refusal but then defaults to proxying on port 6881, even though the docker-compose.yml specifies port 8080.

Here’s an excerpt from the logs:

```
tsdproxy       | 5:38PM INF request host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent
 status=200 url=/assets/Dashboard-DYOhHL9P.js
tsdproxy       | 5:38PM INF request host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent
 status=200 url=/assets/ColoredChip.vue_vue_type_script_setup_true_lang-DosC_URk.js
tsdproxy       | 5:38PM INF request host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent
 status=200 url=/assets/TagFormDialog.vue_vue_type_script_setup_true_lang-DdjOLo6r.js
tsdproxy       | 5:38PM ERR error host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent status=500 url=/backend/ping
tsdproxy       | 5:38PM INF request host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent
 status=200 url=/api/v2/sync/maindata?rid=1
tsdproxy       | 2024/12/11 17:38:38 http: proxy error: dial tcp 172.18.0.3:8080: connect: connection refused
tsdproxy       | 5:38PM ERR error host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent status=502 url=/api/v2/sync/maindata?rid=2
tsdproxy       | 5:38PM INF Container f02d466ffed6e173b17057cba723bd188762f81ac790836cb4cf10d5cb25b3d5 stopped docker=local
 module=proxymanager
tsdproxy       | 5:38PM INF stopping proxy module=proxymanager name=qbittorrent proxyname=qbittorrent
tsdproxy       | 5:38PM INF Proxy server shut down successfully module=proxymanager proxy=qbittorrent
tsdproxy       | 5:38PM INF Removed proxy for container module=proxymanager proxy=qbittorrent
tsdproxy       | 5:38PM INF Container f02d466ffed6e173b17057cba723bd188762f81ac790836cb4cf10d5cb25b3d5 started docker=local
 module=proxymanager
tsdproxy       | 5:38PM INF Trying to auto detect target URL container=/qbittorrent docker=local module=proxymanager try=0
tsdproxy       | 5:38PM INF Successfully connected using docker network gateway and exposed port address=172.18.0.1 container=/qbittorrent docker=local module=proxymanager port=6881
tsdproxy       | 5:38PM INF setting up proxy hostname=qbittorrent module=proxymanager
tsdproxy       | 5:38PM INF starting proxy module=proxymanager name=qbittorrent proxyname=qbittorrent
tsdproxy       | 5:38PM INF tsnet running state path /data/default/qbittorrent/tailscaled.state module=proxymanager tailscale=default
tsdproxy       | 5:38PM INF tsnet starting with hostname "qbittorrent", varRoot "/data/default/qbittorrent" module=proxymanager tailscale=default
tsdproxy       | 5:38PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
tsdproxy       | 5:38PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
tsdproxy       | 2024/12/11 17:38:43 http: proxy error: EOF
tsdproxy       | 5:38PM ERR error host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent status=502 url=/api/v2/sync/maindata?rid=2
tsdproxy       | 5:38PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
tsdproxy       | 2024/12/11 17:38:48 http: proxy error: EOF
tsdproxy       | 5:38PM ERR error host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent status=502 url=/api/v2/sync/maindata?rid=2
tsdproxy       | 2024/12/11 17:38:52 http: proxy error: EOF
tsdproxy       | 5:38PM ERR error host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent status=502 url=/
tsdproxy       | 2024/12/11 17:38:53 http: proxy error: EOF
tsdproxy       | 5:38PM ERR error host=qbittorrent.kudu-eagle.ts.net method=GET module=proxymanager proxyname=qbittorrent status=502 url=/sw.js
```

Restarting TSDProxy resolves the issue, and it correctly uses port 8080 again. However, it would be ideal if TSDProxy consistently adhered to the defined port in the docker-compose.yml, even after the qBittorrent container is restarted.
