### ISSUE TITLE
No Target Providers found module=proxymanager

### ISSUE THREAD

**Issue by slockers37** [almeidapaulopt/tsdproxy#99]
I'm using Ubuntu 22.04 x86 system with the following docker compose

```yaml
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
volumes:
  datadir:
``` 
Also the `tsdproxy.yaml` is formatted as

```yaml
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        defaultproxyprovider: default
tailscale:
    providers:
        default:
            authkey: tskey-auth-...
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyaccesslog: true
``` 

P.S.: I am a noob so maybe it is something very simple. I just didn’t find any other place to ask the question.

**Comment by StealthBadger747** [comment]
I'm getting the same error

**Comment by jandrews377** [comment]
I am getting the exact same error:
```
tsdproxy-mediastack  | Initializing server
tsdproxy-mediastack  | Version 
tsdproxy-mediastack  | loading configuration from: /config/tsdproxy.yaml
tsdproxy-mediastack  | Validating configuration...
tsdproxy-mediastack  | Setting up logger
tsdproxy-mediastack  | 10:31PM INF Log Settings Log level=info
tsdproxy-mediastack  | 10:31PM INF Starting server Version=
tsdproxy-mediastack  | 10:31PM INF Setting up proxy proxies
tsdproxy-mediastack  | 10:31PM INF Initializing WebServer
tsdproxy-mediastack  | 10:31PM INF Health check set to ready
tsdproxy-mediastack  | 10:31PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
tsdproxy-mediastack  | 10:31PM ERR No Target Providers found module=proxymanager
```

In my case I am using headscale. My config looks like (key ommitted):
```
defaultproxyprovider: headscale
docker:
  local:
    host: unix:///var/run/docker.sock
    targethostname: 172.31.0.1
    defaultproxyprovider: headscale
files: {}
tailscale:
  providers:
    headscale:
      authkey: {KEY OMMITTED}
      authkeyfile: ""
      controlurl: http://10.1.1.1:8080
  datadir: /data/
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info
  json: false
proxyaccesslog: true
```
